[package]
name = "unicorn86"
version = "2.0.0"
authors =  [ "moonshadow565" ]
license = "GPL v2"
edition = "2018"
categories = [ "api-bindings" ]

[dependencies.bitflags]
version = "1.3"

[build-dependencies.cmake]
version = "0.1"
