/* automatically generated by rust-bindgen 0.59.2 */

#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(dead_code)]

#[repr(C)]
#[derive(Debug)]
pub struct uc_engine {
    _unused: [u8; 0],
}
pub type uc_hook = usize;
pub const UC_CPU_X86_QEMU64: uc_cpu_x86 = 0;
pub const UC_CPU_X86_PHENOM: uc_cpu_x86 = 1;
pub const UC_CPU_X86_CORE2DUO: uc_cpu_x86 = 2;
pub const UC_CPU_X86_KVM64: uc_cpu_x86 = 3;
pub const UC_CPU_X86_QEMU32: uc_cpu_x86 = 4;
pub const UC_CPU_X86_KVM32: uc_cpu_x86 = 5;
pub const UC_CPU_X86_COREDUO: uc_cpu_x86 = 6;
pub const UC_CPU_X86_486: uc_cpu_x86 = 7;
pub const UC_CPU_X86_PENTIUM: uc_cpu_x86 = 8;
pub const UC_CPU_X86_PENTIUM2: uc_cpu_x86 = 9;
pub const UC_CPU_X86_PENTIUM3: uc_cpu_x86 = 10;
pub const UC_CPU_X86_ATHLON: uc_cpu_x86 = 11;
pub const UC_CPU_X86_N270: uc_cpu_x86 = 12;
pub const UC_CPU_X86_CONROE: uc_cpu_x86 = 13;
pub const UC_CPU_X86_PENRYN: uc_cpu_x86 = 14;
pub const UC_CPU_X86_NEHALEM: uc_cpu_x86 = 15;
pub const UC_CPU_X86_WESTMERE: uc_cpu_x86 = 16;
pub const UC_CPU_X86_SANDYBRIDGE: uc_cpu_x86 = 17;
pub const UC_CPU_X86_IVYBRIDGE: uc_cpu_x86 = 18;
pub const UC_CPU_X86_HASWELL: uc_cpu_x86 = 19;
pub const UC_CPU_X86_BROADWELL: uc_cpu_x86 = 20;
pub const UC_CPU_X86_SKYLAKE_CLIENT: uc_cpu_x86 = 21;
pub const UC_CPU_X86_SKYLAKE_SERVER: uc_cpu_x86 = 22;
pub const UC_CPU_X86_CASCADELAKE_SERVER: uc_cpu_x86 = 23;
pub const UC_CPU_X86_COOPERLAKE: uc_cpu_x86 = 24;
pub const UC_CPU_X86_ICELAKE_CLIENT: uc_cpu_x86 = 25;
pub const UC_CPU_X86_ICELAKE_SERVER: uc_cpu_x86 = 26;
pub const UC_CPU_X86_DENVERTON: uc_cpu_x86 = 27;
pub const UC_CPU_X86_SNOWRIDGE: uc_cpu_x86 = 28;
pub const UC_CPU_X86_KNIGHTSMILL: uc_cpu_x86 = 29;
pub const UC_CPU_X86_OPTERON_G1: uc_cpu_x86 = 30;
pub const UC_CPU_X86_OPTERON_G2: uc_cpu_x86 = 31;
pub const UC_CPU_X86_OPTERON_G3: uc_cpu_x86 = 32;
pub const UC_CPU_X86_OPTERON_G4: uc_cpu_x86 = 33;
pub const UC_CPU_X86_OPTERON_G5: uc_cpu_x86 = 34;
pub const UC_CPU_X86_EPYC: uc_cpu_x86 = 35;
pub const UC_CPU_X86_DHYANA: uc_cpu_x86 = 36;
pub const UC_CPU_X86_EPYC_ROME: uc_cpu_x86 = 37;
pub type uc_cpu_x86 = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uc_x86_mmr {
    pub selector: u16,
    pub base: u64,
    pub limit: u32,
    pub flags: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uc_x86_msr {
    pub rid: u32,
    pub value: u64,
}
pub type uc_cb_insn_syscall_t = ::core::option::Option<
    unsafe extern "C" fn(uc: *mut uc_engine, user_data: *mut ::core::ffi::c_void),
>;
pub const UC_X86_REG_INVALID: uc_x86_reg = 0;
pub const UC_X86_REG_AH: uc_x86_reg = 1;
pub const UC_X86_REG_AL: uc_x86_reg = 2;
pub const UC_X86_REG_AX: uc_x86_reg = 3;
pub const UC_X86_REG_BH: uc_x86_reg = 4;
pub const UC_X86_REG_BL: uc_x86_reg = 5;
pub const UC_X86_REG_BP: uc_x86_reg = 6;
pub const UC_X86_REG_BPL: uc_x86_reg = 7;
pub const UC_X86_REG_BX: uc_x86_reg = 8;
pub const UC_X86_REG_CH: uc_x86_reg = 9;
pub const UC_X86_REG_CL: uc_x86_reg = 10;
pub const UC_X86_REG_CS: uc_x86_reg = 11;
pub const UC_X86_REG_CX: uc_x86_reg = 12;
pub const UC_X86_REG_DH: uc_x86_reg = 13;
pub const UC_X86_REG_DI: uc_x86_reg = 14;
pub const UC_X86_REG_DIL: uc_x86_reg = 15;
pub const UC_X86_REG_DL: uc_x86_reg = 16;
pub const UC_X86_REG_DS: uc_x86_reg = 17;
pub const UC_X86_REG_DX: uc_x86_reg = 18;
pub const UC_X86_REG_EAX: uc_x86_reg = 19;
pub const UC_X86_REG_EBP: uc_x86_reg = 20;
pub const UC_X86_REG_EBX: uc_x86_reg = 21;
pub const UC_X86_REG_ECX: uc_x86_reg = 22;
pub const UC_X86_REG_EDI: uc_x86_reg = 23;
pub const UC_X86_REG_EDX: uc_x86_reg = 24;
pub const UC_X86_REG_EFLAGS: uc_x86_reg = 25;
pub const UC_X86_REG_EIP: uc_x86_reg = 26;
pub const UC_X86_REG_ES: uc_x86_reg = 27;
pub const UC_X86_REG_ESI: uc_x86_reg = 28;
pub const UC_X86_REG_ESP: uc_x86_reg = 29;
pub const UC_X86_REG_FPSW: uc_x86_reg = 30;
pub const UC_X86_REG_FS: uc_x86_reg = 31;
pub const UC_X86_REG_GS: uc_x86_reg = 32;
pub const UC_X86_REG_IP: uc_x86_reg = 33;
pub const UC_X86_REG_RAX: uc_x86_reg = 34;
pub const UC_X86_REG_RBP: uc_x86_reg = 35;
pub const UC_X86_REG_RBX: uc_x86_reg = 36;
pub const UC_X86_REG_RCX: uc_x86_reg = 37;
pub const UC_X86_REG_RDI: uc_x86_reg = 38;
pub const UC_X86_REG_RDX: uc_x86_reg = 39;
pub const UC_X86_REG_RIP: uc_x86_reg = 40;
pub const UC_X86_REG_RSI: uc_x86_reg = 41;
pub const UC_X86_REG_RSP: uc_x86_reg = 42;
pub const UC_X86_REG_SI: uc_x86_reg = 43;
pub const UC_X86_REG_SIL: uc_x86_reg = 44;
pub const UC_X86_REG_SP: uc_x86_reg = 45;
pub const UC_X86_REG_SPL: uc_x86_reg = 46;
pub const UC_X86_REG_SS: uc_x86_reg = 47;
pub const UC_X86_REG_CR0: uc_x86_reg = 48;
pub const UC_X86_REG_CR1: uc_x86_reg = 49;
pub const UC_X86_REG_CR2: uc_x86_reg = 50;
pub const UC_X86_REG_CR3: uc_x86_reg = 51;
pub const UC_X86_REG_CR4: uc_x86_reg = 52;
pub const UC_X86_REG_CR8: uc_x86_reg = 53;
pub const UC_X86_REG_DR0: uc_x86_reg = 54;
pub const UC_X86_REG_DR1: uc_x86_reg = 55;
pub const UC_X86_REG_DR2: uc_x86_reg = 56;
pub const UC_X86_REG_DR3: uc_x86_reg = 57;
pub const UC_X86_REG_DR4: uc_x86_reg = 58;
pub const UC_X86_REG_DR5: uc_x86_reg = 59;
pub const UC_X86_REG_DR6: uc_x86_reg = 60;
pub const UC_X86_REG_DR7: uc_x86_reg = 61;
pub const UC_X86_REG_FP0: uc_x86_reg = 62;
pub const UC_X86_REG_FP1: uc_x86_reg = 63;
pub const UC_X86_REG_FP2: uc_x86_reg = 64;
pub const UC_X86_REG_FP3: uc_x86_reg = 65;
pub const UC_X86_REG_FP4: uc_x86_reg = 66;
pub const UC_X86_REG_FP5: uc_x86_reg = 67;
pub const UC_X86_REG_FP6: uc_x86_reg = 68;
pub const UC_X86_REG_FP7: uc_x86_reg = 69;
pub const UC_X86_REG_K0: uc_x86_reg = 70;
pub const UC_X86_REG_K1: uc_x86_reg = 71;
pub const UC_X86_REG_K2: uc_x86_reg = 72;
pub const UC_X86_REG_K3: uc_x86_reg = 73;
pub const UC_X86_REG_K4: uc_x86_reg = 74;
pub const UC_X86_REG_K5: uc_x86_reg = 75;
pub const UC_X86_REG_K6: uc_x86_reg = 76;
pub const UC_X86_REG_K7: uc_x86_reg = 77;
pub const UC_X86_REG_MM0: uc_x86_reg = 78;
pub const UC_X86_REG_MM1: uc_x86_reg = 79;
pub const UC_X86_REG_MM2: uc_x86_reg = 80;
pub const UC_X86_REG_MM3: uc_x86_reg = 81;
pub const UC_X86_REG_MM4: uc_x86_reg = 82;
pub const UC_X86_REG_MM5: uc_x86_reg = 83;
pub const UC_X86_REG_MM6: uc_x86_reg = 84;
pub const UC_X86_REG_MM7: uc_x86_reg = 85;
pub const UC_X86_REG_R8: uc_x86_reg = 86;
pub const UC_X86_REG_R9: uc_x86_reg = 87;
pub const UC_X86_REG_R10: uc_x86_reg = 88;
pub const UC_X86_REG_R11: uc_x86_reg = 89;
pub const UC_X86_REG_R12: uc_x86_reg = 90;
pub const UC_X86_REG_R13: uc_x86_reg = 91;
pub const UC_X86_REG_R14: uc_x86_reg = 92;
pub const UC_X86_REG_R15: uc_x86_reg = 93;
pub const UC_X86_REG_ST0: uc_x86_reg = 94;
pub const UC_X86_REG_ST1: uc_x86_reg = 95;
pub const UC_X86_REG_ST2: uc_x86_reg = 96;
pub const UC_X86_REG_ST3: uc_x86_reg = 97;
pub const UC_X86_REG_ST4: uc_x86_reg = 98;
pub const UC_X86_REG_ST5: uc_x86_reg = 99;
pub const UC_X86_REG_ST6: uc_x86_reg = 100;
pub const UC_X86_REG_ST7: uc_x86_reg = 101;
pub const UC_X86_REG_XMM0: uc_x86_reg = 102;
pub const UC_X86_REG_XMM1: uc_x86_reg = 103;
pub const UC_X86_REG_XMM2: uc_x86_reg = 104;
pub const UC_X86_REG_XMM3: uc_x86_reg = 105;
pub const UC_X86_REG_XMM4: uc_x86_reg = 106;
pub const UC_X86_REG_XMM5: uc_x86_reg = 107;
pub const UC_X86_REG_XMM6: uc_x86_reg = 108;
pub const UC_X86_REG_XMM7: uc_x86_reg = 109;
pub const UC_X86_REG_XMM8: uc_x86_reg = 110;
pub const UC_X86_REG_XMM9: uc_x86_reg = 111;
pub const UC_X86_REG_XMM10: uc_x86_reg = 112;
pub const UC_X86_REG_XMM11: uc_x86_reg = 113;
pub const UC_X86_REG_XMM12: uc_x86_reg = 114;
pub const UC_X86_REG_XMM13: uc_x86_reg = 115;
pub const UC_X86_REG_XMM14: uc_x86_reg = 116;
pub const UC_X86_REG_XMM15: uc_x86_reg = 117;
pub const UC_X86_REG_XMM16: uc_x86_reg = 118;
pub const UC_X86_REG_XMM17: uc_x86_reg = 119;
pub const UC_X86_REG_XMM18: uc_x86_reg = 120;
pub const UC_X86_REG_XMM19: uc_x86_reg = 121;
pub const UC_X86_REG_XMM20: uc_x86_reg = 122;
pub const UC_X86_REG_XMM21: uc_x86_reg = 123;
pub const UC_X86_REG_XMM22: uc_x86_reg = 124;
pub const UC_X86_REG_XMM23: uc_x86_reg = 125;
pub const UC_X86_REG_XMM24: uc_x86_reg = 126;
pub const UC_X86_REG_XMM25: uc_x86_reg = 127;
pub const UC_X86_REG_XMM26: uc_x86_reg = 128;
pub const UC_X86_REG_XMM27: uc_x86_reg = 129;
pub const UC_X86_REG_XMM28: uc_x86_reg = 130;
pub const UC_X86_REG_XMM29: uc_x86_reg = 131;
pub const UC_X86_REG_XMM30: uc_x86_reg = 132;
pub const UC_X86_REG_XMM31: uc_x86_reg = 133;
pub const UC_X86_REG_YMM0: uc_x86_reg = 134;
pub const UC_X86_REG_YMM1: uc_x86_reg = 135;
pub const UC_X86_REG_YMM2: uc_x86_reg = 136;
pub const UC_X86_REG_YMM3: uc_x86_reg = 137;
pub const UC_X86_REG_YMM4: uc_x86_reg = 138;
pub const UC_X86_REG_YMM5: uc_x86_reg = 139;
pub const UC_X86_REG_YMM6: uc_x86_reg = 140;
pub const UC_X86_REG_YMM7: uc_x86_reg = 141;
pub const UC_X86_REG_YMM8: uc_x86_reg = 142;
pub const UC_X86_REG_YMM9: uc_x86_reg = 143;
pub const UC_X86_REG_YMM10: uc_x86_reg = 144;
pub const UC_X86_REG_YMM11: uc_x86_reg = 145;
pub const UC_X86_REG_YMM12: uc_x86_reg = 146;
pub const UC_X86_REG_YMM13: uc_x86_reg = 147;
pub const UC_X86_REG_YMM14: uc_x86_reg = 148;
pub const UC_X86_REG_YMM15: uc_x86_reg = 149;
pub const UC_X86_REG_YMM16: uc_x86_reg = 150;
pub const UC_X86_REG_YMM17: uc_x86_reg = 151;
pub const UC_X86_REG_YMM18: uc_x86_reg = 152;
pub const UC_X86_REG_YMM19: uc_x86_reg = 153;
pub const UC_X86_REG_YMM20: uc_x86_reg = 154;
pub const UC_X86_REG_YMM21: uc_x86_reg = 155;
pub const UC_X86_REG_YMM22: uc_x86_reg = 156;
pub const UC_X86_REG_YMM23: uc_x86_reg = 157;
pub const UC_X86_REG_YMM24: uc_x86_reg = 158;
pub const UC_X86_REG_YMM25: uc_x86_reg = 159;
pub const UC_X86_REG_YMM26: uc_x86_reg = 160;
pub const UC_X86_REG_YMM27: uc_x86_reg = 161;
pub const UC_X86_REG_YMM28: uc_x86_reg = 162;
pub const UC_X86_REG_YMM29: uc_x86_reg = 163;
pub const UC_X86_REG_YMM30: uc_x86_reg = 164;
pub const UC_X86_REG_YMM31: uc_x86_reg = 165;
pub const UC_X86_REG_ZMM0: uc_x86_reg = 166;
pub const UC_X86_REG_ZMM1: uc_x86_reg = 167;
pub const UC_X86_REG_ZMM2: uc_x86_reg = 168;
pub const UC_X86_REG_ZMM3: uc_x86_reg = 169;
pub const UC_X86_REG_ZMM4: uc_x86_reg = 170;
pub const UC_X86_REG_ZMM5: uc_x86_reg = 171;
pub const UC_X86_REG_ZMM6: uc_x86_reg = 172;
pub const UC_X86_REG_ZMM7: uc_x86_reg = 173;
pub const UC_X86_REG_ZMM8: uc_x86_reg = 174;
pub const UC_X86_REG_ZMM9: uc_x86_reg = 175;
pub const UC_X86_REG_ZMM10: uc_x86_reg = 176;
pub const UC_X86_REG_ZMM11: uc_x86_reg = 177;
pub const UC_X86_REG_ZMM12: uc_x86_reg = 178;
pub const UC_X86_REG_ZMM13: uc_x86_reg = 179;
pub const UC_X86_REG_ZMM14: uc_x86_reg = 180;
pub const UC_X86_REG_ZMM15: uc_x86_reg = 181;
pub const UC_X86_REG_ZMM16: uc_x86_reg = 182;
pub const UC_X86_REG_ZMM17: uc_x86_reg = 183;
pub const UC_X86_REG_ZMM18: uc_x86_reg = 184;
pub const UC_X86_REG_ZMM19: uc_x86_reg = 185;
pub const UC_X86_REG_ZMM20: uc_x86_reg = 186;
pub const UC_X86_REG_ZMM21: uc_x86_reg = 187;
pub const UC_X86_REG_ZMM22: uc_x86_reg = 188;
pub const UC_X86_REG_ZMM23: uc_x86_reg = 189;
pub const UC_X86_REG_ZMM24: uc_x86_reg = 190;
pub const UC_X86_REG_ZMM25: uc_x86_reg = 191;
pub const UC_X86_REG_ZMM26: uc_x86_reg = 192;
pub const UC_X86_REG_ZMM27: uc_x86_reg = 193;
pub const UC_X86_REG_ZMM28: uc_x86_reg = 194;
pub const UC_X86_REG_ZMM29: uc_x86_reg = 195;
pub const UC_X86_REG_ZMM30: uc_x86_reg = 196;
pub const UC_X86_REG_ZMM31: uc_x86_reg = 197;
pub const UC_X86_REG_R8B: uc_x86_reg = 198;
pub const UC_X86_REG_R9B: uc_x86_reg = 199;
pub const UC_X86_REG_R10B: uc_x86_reg = 200;
pub const UC_X86_REG_R11B: uc_x86_reg = 201;
pub const UC_X86_REG_R12B: uc_x86_reg = 202;
pub const UC_X86_REG_R13B: uc_x86_reg = 203;
pub const UC_X86_REG_R14B: uc_x86_reg = 204;
pub const UC_X86_REG_R15B: uc_x86_reg = 205;
pub const UC_X86_REG_R8D: uc_x86_reg = 206;
pub const UC_X86_REG_R9D: uc_x86_reg = 207;
pub const UC_X86_REG_R10D: uc_x86_reg = 208;
pub const UC_X86_REG_R11D: uc_x86_reg = 209;
pub const UC_X86_REG_R12D: uc_x86_reg = 210;
pub const UC_X86_REG_R13D: uc_x86_reg = 211;
pub const UC_X86_REG_R14D: uc_x86_reg = 212;
pub const UC_X86_REG_R15D: uc_x86_reg = 213;
pub const UC_X86_REG_R8W: uc_x86_reg = 214;
pub const UC_X86_REG_R9W: uc_x86_reg = 215;
pub const UC_X86_REG_R10W: uc_x86_reg = 216;
pub const UC_X86_REG_R11W: uc_x86_reg = 217;
pub const UC_X86_REG_R12W: uc_x86_reg = 218;
pub const UC_X86_REG_R13W: uc_x86_reg = 219;
pub const UC_X86_REG_R14W: uc_x86_reg = 220;
pub const UC_X86_REG_R15W: uc_x86_reg = 221;
pub const UC_X86_REG_IDTR: uc_x86_reg = 222;
pub const UC_X86_REG_GDTR: uc_x86_reg = 223;
pub const UC_X86_REG_LDTR: uc_x86_reg = 224;
pub const UC_X86_REG_TR: uc_x86_reg = 225;
pub const UC_X86_REG_FPCW: uc_x86_reg = 226;
pub const UC_X86_REG_FPTAG: uc_x86_reg = 227;
pub const UC_X86_REG_MSR: uc_x86_reg = 228;
pub const UC_X86_REG_MXCSR: uc_x86_reg = 229;
pub const UC_X86_REG_FS_BASE: uc_x86_reg = 230;
pub const UC_X86_REG_GS_BASE: uc_x86_reg = 231;
pub const UC_X86_REG_FLAGS: uc_x86_reg = 232;
pub const UC_X86_REG_RFLAGS: uc_x86_reg = 233;
pub const UC_X86_REG_ENDING: uc_x86_reg = 234;
pub type uc_x86_reg = ::std::os::raw::c_int;
pub const UC_X86_INS_INVALID: uc_x86_insn = 0;
pub const UC_X86_INS_AAA: uc_x86_insn = 1;
pub const UC_X86_INS_AAD: uc_x86_insn = 2;
pub const UC_X86_INS_AAM: uc_x86_insn = 3;
pub const UC_X86_INS_AAS: uc_x86_insn = 4;
pub const UC_X86_INS_FABS: uc_x86_insn = 5;
pub const UC_X86_INS_ADC: uc_x86_insn = 6;
pub const UC_X86_INS_ADCX: uc_x86_insn = 7;
pub const UC_X86_INS_ADD: uc_x86_insn = 8;
pub const UC_X86_INS_ADDPD: uc_x86_insn = 9;
pub const UC_X86_INS_ADDPS: uc_x86_insn = 10;
pub const UC_X86_INS_ADDSD: uc_x86_insn = 11;
pub const UC_X86_INS_ADDSS: uc_x86_insn = 12;
pub const UC_X86_INS_ADDSUBPD: uc_x86_insn = 13;
pub const UC_X86_INS_ADDSUBPS: uc_x86_insn = 14;
pub const UC_X86_INS_FADD: uc_x86_insn = 15;
pub const UC_X86_INS_FIADD: uc_x86_insn = 16;
pub const UC_X86_INS_FADDP: uc_x86_insn = 17;
pub const UC_X86_INS_ADOX: uc_x86_insn = 18;
pub const UC_X86_INS_AESDECLAST: uc_x86_insn = 19;
pub const UC_X86_INS_AESDEC: uc_x86_insn = 20;
pub const UC_X86_INS_AESENCLAST: uc_x86_insn = 21;
pub const UC_X86_INS_AESENC: uc_x86_insn = 22;
pub const UC_X86_INS_AESIMC: uc_x86_insn = 23;
pub const UC_X86_INS_AESKEYGENASSIST: uc_x86_insn = 24;
pub const UC_X86_INS_AND: uc_x86_insn = 25;
pub const UC_X86_INS_ANDN: uc_x86_insn = 26;
pub const UC_X86_INS_ANDNPD: uc_x86_insn = 27;
pub const UC_X86_INS_ANDNPS: uc_x86_insn = 28;
pub const UC_X86_INS_ANDPD: uc_x86_insn = 29;
pub const UC_X86_INS_ANDPS: uc_x86_insn = 30;
pub const UC_X86_INS_ARPL: uc_x86_insn = 31;
pub const UC_X86_INS_BEXTR: uc_x86_insn = 32;
pub const UC_X86_INS_BLCFILL: uc_x86_insn = 33;
pub const UC_X86_INS_BLCI: uc_x86_insn = 34;
pub const UC_X86_INS_BLCIC: uc_x86_insn = 35;
pub const UC_X86_INS_BLCMSK: uc_x86_insn = 36;
pub const UC_X86_INS_BLCS: uc_x86_insn = 37;
pub const UC_X86_INS_BLENDPD: uc_x86_insn = 38;
pub const UC_X86_INS_BLENDPS: uc_x86_insn = 39;
pub const UC_X86_INS_BLENDVPD: uc_x86_insn = 40;
pub const UC_X86_INS_BLENDVPS: uc_x86_insn = 41;
pub const UC_X86_INS_BLSFILL: uc_x86_insn = 42;
pub const UC_X86_INS_BLSI: uc_x86_insn = 43;
pub const UC_X86_INS_BLSIC: uc_x86_insn = 44;
pub const UC_X86_INS_BLSMSK: uc_x86_insn = 45;
pub const UC_X86_INS_BLSR: uc_x86_insn = 46;
pub const UC_X86_INS_BOUND: uc_x86_insn = 47;
pub const UC_X86_INS_BSF: uc_x86_insn = 48;
pub const UC_X86_INS_BSR: uc_x86_insn = 49;
pub const UC_X86_INS_BSWAP: uc_x86_insn = 50;
pub const UC_X86_INS_BT: uc_x86_insn = 51;
pub const UC_X86_INS_BTC: uc_x86_insn = 52;
pub const UC_X86_INS_BTR: uc_x86_insn = 53;
pub const UC_X86_INS_BTS: uc_x86_insn = 54;
pub const UC_X86_INS_BZHI: uc_x86_insn = 55;
pub const UC_X86_INS_CALL: uc_x86_insn = 56;
pub const UC_X86_INS_CBW: uc_x86_insn = 57;
pub const UC_X86_INS_CDQ: uc_x86_insn = 58;
pub const UC_X86_INS_CDQE: uc_x86_insn = 59;
pub const UC_X86_INS_FCHS: uc_x86_insn = 60;
pub const UC_X86_INS_CLAC: uc_x86_insn = 61;
pub const UC_X86_INS_CLC: uc_x86_insn = 62;
pub const UC_X86_INS_CLD: uc_x86_insn = 63;
pub const UC_X86_INS_CLFLUSH: uc_x86_insn = 64;
pub const UC_X86_INS_CLFLUSHOPT: uc_x86_insn = 65;
pub const UC_X86_INS_CLGI: uc_x86_insn = 66;
pub const UC_X86_INS_CLI: uc_x86_insn = 67;
pub const UC_X86_INS_CLTS: uc_x86_insn = 68;
pub const UC_X86_INS_CLWB: uc_x86_insn = 69;
pub const UC_X86_INS_CMC: uc_x86_insn = 70;
pub const UC_X86_INS_CMOVA: uc_x86_insn = 71;
pub const UC_X86_INS_CMOVAE: uc_x86_insn = 72;
pub const UC_X86_INS_CMOVB: uc_x86_insn = 73;
pub const UC_X86_INS_CMOVBE: uc_x86_insn = 74;
pub const UC_X86_INS_FCMOVBE: uc_x86_insn = 75;
pub const UC_X86_INS_FCMOVB: uc_x86_insn = 76;
pub const UC_X86_INS_CMOVE: uc_x86_insn = 77;
pub const UC_X86_INS_FCMOVE: uc_x86_insn = 78;
pub const UC_X86_INS_CMOVG: uc_x86_insn = 79;
pub const UC_X86_INS_CMOVGE: uc_x86_insn = 80;
pub const UC_X86_INS_CMOVL: uc_x86_insn = 81;
pub const UC_X86_INS_CMOVLE: uc_x86_insn = 82;
pub const UC_X86_INS_FCMOVNBE: uc_x86_insn = 83;
pub const UC_X86_INS_FCMOVNB: uc_x86_insn = 84;
pub const UC_X86_INS_CMOVNE: uc_x86_insn = 85;
pub const UC_X86_INS_FCMOVNE: uc_x86_insn = 86;
pub const UC_X86_INS_CMOVNO: uc_x86_insn = 87;
pub const UC_X86_INS_CMOVNP: uc_x86_insn = 88;
pub const UC_X86_INS_FCMOVNU: uc_x86_insn = 89;
pub const UC_X86_INS_CMOVNS: uc_x86_insn = 90;
pub const UC_X86_INS_CMOVO: uc_x86_insn = 91;
pub const UC_X86_INS_CMOVP: uc_x86_insn = 92;
pub const UC_X86_INS_FCMOVU: uc_x86_insn = 93;
pub const UC_X86_INS_CMOVS: uc_x86_insn = 94;
pub const UC_X86_INS_CMP: uc_x86_insn = 95;
pub const UC_X86_INS_CMPPD: uc_x86_insn = 96;
pub const UC_X86_INS_CMPPS: uc_x86_insn = 97;
pub const UC_X86_INS_CMPSB: uc_x86_insn = 98;
pub const UC_X86_INS_CMPSD: uc_x86_insn = 99;
pub const UC_X86_INS_CMPSQ: uc_x86_insn = 100;
pub const UC_X86_INS_CMPSS: uc_x86_insn = 101;
pub const UC_X86_INS_CMPSW: uc_x86_insn = 102;
pub const UC_X86_INS_CMPXCHG16B: uc_x86_insn = 103;
pub const UC_X86_INS_CMPXCHG: uc_x86_insn = 104;
pub const UC_X86_INS_CMPXCHG8B: uc_x86_insn = 105;
pub const UC_X86_INS_COMISD: uc_x86_insn = 106;
pub const UC_X86_INS_COMISS: uc_x86_insn = 107;
pub const UC_X86_INS_FCOMP: uc_x86_insn = 108;
pub const UC_X86_INS_FCOMPI: uc_x86_insn = 109;
pub const UC_X86_INS_FCOMI: uc_x86_insn = 110;
pub const UC_X86_INS_FCOM: uc_x86_insn = 111;
pub const UC_X86_INS_FCOS: uc_x86_insn = 112;
pub const UC_X86_INS_CPUID: uc_x86_insn = 113;
pub const UC_X86_INS_CQO: uc_x86_insn = 114;
pub const UC_X86_INS_CRC32: uc_x86_insn = 115;
pub const UC_X86_INS_CVTDQ2PD: uc_x86_insn = 116;
pub const UC_X86_INS_CVTDQ2PS: uc_x86_insn = 117;
pub const UC_X86_INS_CVTPD2DQ: uc_x86_insn = 118;
pub const UC_X86_INS_CVTPD2PS: uc_x86_insn = 119;
pub const UC_X86_INS_CVTPS2DQ: uc_x86_insn = 120;
pub const UC_X86_INS_CVTPS2PD: uc_x86_insn = 121;
pub const UC_X86_INS_CVTSD2SI: uc_x86_insn = 122;
pub const UC_X86_INS_CVTSD2SS: uc_x86_insn = 123;
pub const UC_X86_INS_CVTSI2SD: uc_x86_insn = 124;
pub const UC_X86_INS_CVTSI2SS: uc_x86_insn = 125;
pub const UC_X86_INS_CVTSS2SD: uc_x86_insn = 126;
pub const UC_X86_INS_CVTSS2SI: uc_x86_insn = 127;
pub const UC_X86_INS_CVTTPD2DQ: uc_x86_insn = 128;
pub const UC_X86_INS_CVTTPS2DQ: uc_x86_insn = 129;
pub const UC_X86_INS_CVTTSD2SI: uc_x86_insn = 130;
pub const UC_X86_INS_CVTTSS2SI: uc_x86_insn = 131;
pub const UC_X86_INS_CWD: uc_x86_insn = 132;
pub const UC_X86_INS_CWDE: uc_x86_insn = 133;
pub const UC_X86_INS_DAA: uc_x86_insn = 134;
pub const UC_X86_INS_DAS: uc_x86_insn = 135;
pub const UC_X86_INS_DATA16: uc_x86_insn = 136;
pub const UC_X86_INS_DEC: uc_x86_insn = 137;
pub const UC_X86_INS_DIV: uc_x86_insn = 138;
pub const UC_X86_INS_DIVPD: uc_x86_insn = 139;
pub const UC_X86_INS_DIVPS: uc_x86_insn = 140;
pub const UC_X86_INS_FDIVR: uc_x86_insn = 141;
pub const UC_X86_INS_FIDIVR: uc_x86_insn = 142;
pub const UC_X86_INS_FDIVRP: uc_x86_insn = 143;
pub const UC_X86_INS_DIVSD: uc_x86_insn = 144;
pub const UC_X86_INS_DIVSS: uc_x86_insn = 145;
pub const UC_X86_INS_FDIV: uc_x86_insn = 146;
pub const UC_X86_INS_FIDIV: uc_x86_insn = 147;
pub const UC_X86_INS_FDIVP: uc_x86_insn = 148;
pub const UC_X86_INS_DPPD: uc_x86_insn = 149;
pub const UC_X86_INS_DPPS: uc_x86_insn = 150;
pub const UC_X86_INS_RET: uc_x86_insn = 151;
pub const UC_X86_INS_ENCLS: uc_x86_insn = 152;
pub const UC_X86_INS_ENCLU: uc_x86_insn = 153;
pub const UC_X86_INS_ENTER: uc_x86_insn = 154;
pub const UC_X86_INS_EXTRACTPS: uc_x86_insn = 155;
pub const UC_X86_INS_EXTRQ: uc_x86_insn = 156;
pub const UC_X86_INS_F2XM1: uc_x86_insn = 157;
pub const UC_X86_INS_LCALL: uc_x86_insn = 158;
pub const UC_X86_INS_LJMP: uc_x86_insn = 159;
pub const UC_X86_INS_FBLD: uc_x86_insn = 160;
pub const UC_X86_INS_FBSTP: uc_x86_insn = 161;
pub const UC_X86_INS_FCOMPP: uc_x86_insn = 162;
pub const UC_X86_INS_FDECSTP: uc_x86_insn = 163;
pub const UC_X86_INS_FEMMS: uc_x86_insn = 164;
pub const UC_X86_INS_FFREE: uc_x86_insn = 165;
pub const UC_X86_INS_FICOM: uc_x86_insn = 166;
pub const UC_X86_INS_FICOMP: uc_x86_insn = 167;
pub const UC_X86_INS_FINCSTP: uc_x86_insn = 168;
pub const UC_X86_INS_FLDCW: uc_x86_insn = 169;
pub const UC_X86_INS_FLDENV: uc_x86_insn = 170;
pub const UC_X86_INS_FLDL2E: uc_x86_insn = 171;
pub const UC_X86_INS_FLDL2T: uc_x86_insn = 172;
pub const UC_X86_INS_FLDLG2: uc_x86_insn = 173;
pub const UC_X86_INS_FLDLN2: uc_x86_insn = 174;
pub const UC_X86_INS_FLDPI: uc_x86_insn = 175;
pub const UC_X86_INS_FNCLEX: uc_x86_insn = 176;
pub const UC_X86_INS_FNINIT: uc_x86_insn = 177;
pub const UC_X86_INS_FNOP: uc_x86_insn = 178;
pub const UC_X86_INS_FNSTCW: uc_x86_insn = 179;
pub const UC_X86_INS_FNSTSW: uc_x86_insn = 180;
pub const UC_X86_INS_FPATAN: uc_x86_insn = 181;
pub const UC_X86_INS_FPREM: uc_x86_insn = 182;
pub const UC_X86_INS_FPREM1: uc_x86_insn = 183;
pub const UC_X86_INS_FPTAN: uc_x86_insn = 184;
pub const UC_X86_INS_FFREEP: uc_x86_insn = 185;
pub const UC_X86_INS_FRNDINT: uc_x86_insn = 186;
pub const UC_X86_INS_FRSTOR: uc_x86_insn = 187;
pub const UC_X86_INS_FNSAVE: uc_x86_insn = 188;
pub const UC_X86_INS_FSCALE: uc_x86_insn = 189;
pub const UC_X86_INS_FSETPM: uc_x86_insn = 190;
pub const UC_X86_INS_FSINCOS: uc_x86_insn = 191;
pub const UC_X86_INS_FNSTENV: uc_x86_insn = 192;
pub const UC_X86_INS_FXAM: uc_x86_insn = 193;
pub const UC_X86_INS_FXRSTOR: uc_x86_insn = 194;
pub const UC_X86_INS_FXRSTOR64: uc_x86_insn = 195;
pub const UC_X86_INS_FXSAVE: uc_x86_insn = 196;
pub const UC_X86_INS_FXSAVE64: uc_x86_insn = 197;
pub const UC_X86_INS_FXTRACT: uc_x86_insn = 198;
pub const UC_X86_INS_FYL2X: uc_x86_insn = 199;
pub const UC_X86_INS_FYL2XP1: uc_x86_insn = 200;
pub const UC_X86_INS_MOVAPD: uc_x86_insn = 201;
pub const UC_X86_INS_MOVAPS: uc_x86_insn = 202;
pub const UC_X86_INS_ORPD: uc_x86_insn = 203;
pub const UC_X86_INS_ORPS: uc_x86_insn = 204;
pub const UC_X86_INS_VMOVAPD: uc_x86_insn = 205;
pub const UC_X86_INS_VMOVAPS: uc_x86_insn = 206;
pub const UC_X86_INS_XORPD: uc_x86_insn = 207;
pub const UC_X86_INS_XORPS: uc_x86_insn = 208;
pub const UC_X86_INS_GETSEC: uc_x86_insn = 209;
pub const UC_X86_INS_HADDPD: uc_x86_insn = 210;
pub const UC_X86_INS_HADDPS: uc_x86_insn = 211;
pub const UC_X86_INS_HLT: uc_x86_insn = 212;
pub const UC_X86_INS_HSUBPD: uc_x86_insn = 213;
pub const UC_X86_INS_HSUBPS: uc_x86_insn = 214;
pub const UC_X86_INS_IDIV: uc_x86_insn = 215;
pub const UC_X86_INS_FILD: uc_x86_insn = 216;
pub const UC_X86_INS_IMUL: uc_x86_insn = 217;
pub const UC_X86_INS_IN: uc_x86_insn = 218;
pub const UC_X86_INS_INC: uc_x86_insn = 219;
pub const UC_X86_INS_INSB: uc_x86_insn = 220;
pub const UC_X86_INS_INSERTPS: uc_x86_insn = 221;
pub const UC_X86_INS_INSERTQ: uc_x86_insn = 222;
pub const UC_X86_INS_INSD: uc_x86_insn = 223;
pub const UC_X86_INS_INSW: uc_x86_insn = 224;
pub const UC_X86_INS_INT: uc_x86_insn = 225;
pub const UC_X86_INS_INT1: uc_x86_insn = 226;
pub const UC_X86_INS_INT3: uc_x86_insn = 227;
pub const UC_X86_INS_INTO: uc_x86_insn = 228;
pub const UC_X86_INS_INVD: uc_x86_insn = 229;
pub const UC_X86_INS_INVEPT: uc_x86_insn = 230;
pub const UC_X86_INS_INVLPG: uc_x86_insn = 231;
pub const UC_X86_INS_INVLPGA: uc_x86_insn = 232;
pub const UC_X86_INS_INVPCID: uc_x86_insn = 233;
pub const UC_X86_INS_INVVPID: uc_x86_insn = 234;
pub const UC_X86_INS_IRET: uc_x86_insn = 235;
pub const UC_X86_INS_IRETD: uc_x86_insn = 236;
pub const UC_X86_INS_IRETQ: uc_x86_insn = 237;
pub const UC_X86_INS_FISTTP: uc_x86_insn = 238;
pub const UC_X86_INS_FIST: uc_x86_insn = 239;
pub const UC_X86_INS_FISTP: uc_x86_insn = 240;
pub const UC_X86_INS_UCOMISD: uc_x86_insn = 241;
pub const UC_X86_INS_UCOMISS: uc_x86_insn = 242;
pub const UC_X86_INS_VCOMISD: uc_x86_insn = 243;
pub const UC_X86_INS_VCOMISS: uc_x86_insn = 244;
pub const UC_X86_INS_VCVTSD2SS: uc_x86_insn = 245;
pub const UC_X86_INS_VCVTSI2SD: uc_x86_insn = 246;
pub const UC_X86_INS_VCVTSI2SS: uc_x86_insn = 247;
pub const UC_X86_INS_VCVTSS2SD: uc_x86_insn = 248;
pub const UC_X86_INS_VCVTTSD2SI: uc_x86_insn = 249;
pub const UC_X86_INS_VCVTTSD2USI: uc_x86_insn = 250;
pub const UC_X86_INS_VCVTTSS2SI: uc_x86_insn = 251;
pub const UC_X86_INS_VCVTTSS2USI: uc_x86_insn = 252;
pub const UC_X86_INS_VCVTUSI2SD: uc_x86_insn = 253;
pub const UC_X86_INS_VCVTUSI2SS: uc_x86_insn = 254;
pub const UC_X86_INS_VUCOMISD: uc_x86_insn = 255;
pub const UC_X86_INS_VUCOMISS: uc_x86_insn = 256;
pub const UC_X86_INS_JAE: uc_x86_insn = 257;
pub const UC_X86_INS_JA: uc_x86_insn = 258;
pub const UC_X86_INS_JBE: uc_x86_insn = 259;
pub const UC_X86_INS_JB: uc_x86_insn = 260;
pub const UC_X86_INS_JCXZ: uc_x86_insn = 261;
pub const UC_X86_INS_JECXZ: uc_x86_insn = 262;
pub const UC_X86_INS_JE: uc_x86_insn = 263;
pub const UC_X86_INS_JGE: uc_x86_insn = 264;
pub const UC_X86_INS_JG: uc_x86_insn = 265;
pub const UC_X86_INS_JLE: uc_x86_insn = 266;
pub const UC_X86_INS_JL: uc_x86_insn = 267;
pub const UC_X86_INS_JMP: uc_x86_insn = 268;
pub const UC_X86_INS_JNE: uc_x86_insn = 269;
pub const UC_X86_INS_JNO: uc_x86_insn = 270;
pub const UC_X86_INS_JNP: uc_x86_insn = 271;
pub const UC_X86_INS_JNS: uc_x86_insn = 272;
pub const UC_X86_INS_JO: uc_x86_insn = 273;
pub const UC_X86_INS_JP: uc_x86_insn = 274;
pub const UC_X86_INS_JRCXZ: uc_x86_insn = 275;
pub const UC_X86_INS_JS: uc_x86_insn = 276;
pub const UC_X86_INS_KANDB: uc_x86_insn = 277;
pub const UC_X86_INS_KANDD: uc_x86_insn = 278;
pub const UC_X86_INS_KANDNB: uc_x86_insn = 279;
pub const UC_X86_INS_KANDND: uc_x86_insn = 280;
pub const UC_X86_INS_KANDNQ: uc_x86_insn = 281;
pub const UC_X86_INS_KANDNW: uc_x86_insn = 282;
pub const UC_X86_INS_KANDQ: uc_x86_insn = 283;
pub const UC_X86_INS_KANDW: uc_x86_insn = 284;
pub const UC_X86_INS_KMOVB: uc_x86_insn = 285;
pub const UC_X86_INS_KMOVD: uc_x86_insn = 286;
pub const UC_X86_INS_KMOVQ: uc_x86_insn = 287;
pub const UC_X86_INS_KMOVW: uc_x86_insn = 288;
pub const UC_X86_INS_KNOTB: uc_x86_insn = 289;
pub const UC_X86_INS_KNOTD: uc_x86_insn = 290;
pub const UC_X86_INS_KNOTQ: uc_x86_insn = 291;
pub const UC_X86_INS_KNOTW: uc_x86_insn = 292;
pub const UC_X86_INS_KORB: uc_x86_insn = 293;
pub const UC_X86_INS_KORD: uc_x86_insn = 294;
pub const UC_X86_INS_KORQ: uc_x86_insn = 295;
pub const UC_X86_INS_KORTESTB: uc_x86_insn = 296;
pub const UC_X86_INS_KORTESTD: uc_x86_insn = 297;
pub const UC_X86_INS_KORTESTQ: uc_x86_insn = 298;
pub const UC_X86_INS_KORTESTW: uc_x86_insn = 299;
pub const UC_X86_INS_KORW: uc_x86_insn = 300;
pub const UC_X86_INS_KSHIFTLB: uc_x86_insn = 301;
pub const UC_X86_INS_KSHIFTLD: uc_x86_insn = 302;
pub const UC_X86_INS_KSHIFTLQ: uc_x86_insn = 303;
pub const UC_X86_INS_KSHIFTLW: uc_x86_insn = 304;
pub const UC_X86_INS_KSHIFTRB: uc_x86_insn = 305;
pub const UC_X86_INS_KSHIFTRD: uc_x86_insn = 306;
pub const UC_X86_INS_KSHIFTRQ: uc_x86_insn = 307;
pub const UC_X86_INS_KSHIFTRW: uc_x86_insn = 308;
pub const UC_X86_INS_KUNPCKBW: uc_x86_insn = 309;
pub const UC_X86_INS_KXNORB: uc_x86_insn = 310;
pub const UC_X86_INS_KXNORD: uc_x86_insn = 311;
pub const UC_X86_INS_KXNORQ: uc_x86_insn = 312;
pub const UC_X86_INS_KXNORW: uc_x86_insn = 313;
pub const UC_X86_INS_KXORB: uc_x86_insn = 314;
pub const UC_X86_INS_KXORD: uc_x86_insn = 315;
pub const UC_X86_INS_KXORQ: uc_x86_insn = 316;
pub const UC_X86_INS_KXORW: uc_x86_insn = 317;
pub const UC_X86_INS_LAHF: uc_x86_insn = 318;
pub const UC_X86_INS_LAR: uc_x86_insn = 319;
pub const UC_X86_INS_LDDQU: uc_x86_insn = 320;
pub const UC_X86_INS_LDMXCSR: uc_x86_insn = 321;
pub const UC_X86_INS_LDS: uc_x86_insn = 322;
pub const UC_X86_INS_FLDZ: uc_x86_insn = 323;
pub const UC_X86_INS_FLD1: uc_x86_insn = 324;
pub const UC_X86_INS_FLD: uc_x86_insn = 325;
pub const UC_X86_INS_LEA: uc_x86_insn = 326;
pub const UC_X86_INS_LEAVE: uc_x86_insn = 327;
pub const UC_X86_INS_LES: uc_x86_insn = 328;
pub const UC_X86_INS_LFENCE: uc_x86_insn = 329;
pub const UC_X86_INS_LFS: uc_x86_insn = 330;
pub const UC_X86_INS_LGDT: uc_x86_insn = 331;
pub const UC_X86_INS_LGS: uc_x86_insn = 332;
pub const UC_X86_INS_LIDT: uc_x86_insn = 333;
pub const UC_X86_INS_LLDT: uc_x86_insn = 334;
pub const UC_X86_INS_LMSW: uc_x86_insn = 335;
pub const UC_X86_INS_OR: uc_x86_insn = 336;
pub const UC_X86_INS_SUB: uc_x86_insn = 337;
pub const UC_X86_INS_XOR: uc_x86_insn = 338;
pub const UC_X86_INS_LODSB: uc_x86_insn = 339;
pub const UC_X86_INS_LODSD: uc_x86_insn = 340;
pub const UC_X86_INS_LODSQ: uc_x86_insn = 341;
pub const UC_X86_INS_LODSW: uc_x86_insn = 342;
pub const UC_X86_INS_LOOP: uc_x86_insn = 343;
pub const UC_X86_INS_LOOPE: uc_x86_insn = 344;
pub const UC_X86_INS_LOOPNE: uc_x86_insn = 345;
pub const UC_X86_INS_RETF: uc_x86_insn = 346;
pub const UC_X86_INS_RETFQ: uc_x86_insn = 347;
pub const UC_X86_INS_LSL: uc_x86_insn = 348;
pub const UC_X86_INS_LSS: uc_x86_insn = 349;
pub const UC_X86_INS_LTR: uc_x86_insn = 350;
pub const UC_X86_INS_XADD: uc_x86_insn = 351;
pub const UC_X86_INS_LZCNT: uc_x86_insn = 352;
pub const UC_X86_INS_MASKMOVDQU: uc_x86_insn = 353;
pub const UC_X86_INS_MAXPD: uc_x86_insn = 354;
pub const UC_X86_INS_MAXPS: uc_x86_insn = 355;
pub const UC_X86_INS_MAXSD: uc_x86_insn = 356;
pub const UC_X86_INS_MAXSS: uc_x86_insn = 357;
pub const UC_X86_INS_MFENCE: uc_x86_insn = 358;
pub const UC_X86_INS_MINPD: uc_x86_insn = 359;
pub const UC_X86_INS_MINPS: uc_x86_insn = 360;
pub const UC_X86_INS_MINSD: uc_x86_insn = 361;
pub const UC_X86_INS_MINSS: uc_x86_insn = 362;
pub const UC_X86_INS_CVTPD2PI: uc_x86_insn = 363;
pub const UC_X86_INS_CVTPI2PD: uc_x86_insn = 364;
pub const UC_X86_INS_CVTPI2PS: uc_x86_insn = 365;
pub const UC_X86_INS_CVTPS2PI: uc_x86_insn = 366;
pub const UC_X86_INS_CVTTPD2PI: uc_x86_insn = 367;
pub const UC_X86_INS_CVTTPS2PI: uc_x86_insn = 368;
pub const UC_X86_INS_EMMS: uc_x86_insn = 369;
pub const UC_X86_INS_MASKMOVQ: uc_x86_insn = 370;
pub const UC_X86_INS_MOVD: uc_x86_insn = 371;
pub const UC_X86_INS_MOVDQ2Q: uc_x86_insn = 372;
pub const UC_X86_INS_MOVNTQ: uc_x86_insn = 373;
pub const UC_X86_INS_MOVQ2DQ: uc_x86_insn = 374;
pub const UC_X86_INS_MOVQ: uc_x86_insn = 375;
pub const UC_X86_INS_PABSB: uc_x86_insn = 376;
pub const UC_X86_INS_PABSD: uc_x86_insn = 377;
pub const UC_X86_INS_PABSW: uc_x86_insn = 378;
pub const UC_X86_INS_PACKSSDW: uc_x86_insn = 379;
pub const UC_X86_INS_PACKSSWB: uc_x86_insn = 380;
pub const UC_X86_INS_PACKUSWB: uc_x86_insn = 381;
pub const UC_X86_INS_PADDB: uc_x86_insn = 382;
pub const UC_X86_INS_PADDD: uc_x86_insn = 383;
pub const UC_X86_INS_PADDQ: uc_x86_insn = 384;
pub const UC_X86_INS_PADDSB: uc_x86_insn = 385;
pub const UC_X86_INS_PADDSW: uc_x86_insn = 386;
pub const UC_X86_INS_PADDUSB: uc_x86_insn = 387;
pub const UC_X86_INS_PADDUSW: uc_x86_insn = 388;
pub const UC_X86_INS_PADDW: uc_x86_insn = 389;
pub const UC_X86_INS_PALIGNR: uc_x86_insn = 390;
pub const UC_X86_INS_PANDN: uc_x86_insn = 391;
pub const UC_X86_INS_PAND: uc_x86_insn = 392;
pub const UC_X86_INS_PAVGB: uc_x86_insn = 393;
pub const UC_X86_INS_PAVGW: uc_x86_insn = 394;
pub const UC_X86_INS_PCMPEQB: uc_x86_insn = 395;
pub const UC_X86_INS_PCMPEQD: uc_x86_insn = 396;
pub const UC_X86_INS_PCMPEQW: uc_x86_insn = 397;
pub const UC_X86_INS_PCMPGTB: uc_x86_insn = 398;
pub const UC_X86_INS_PCMPGTD: uc_x86_insn = 399;
pub const UC_X86_INS_PCMPGTW: uc_x86_insn = 400;
pub const UC_X86_INS_PEXTRW: uc_x86_insn = 401;
pub const UC_X86_INS_PHADDSW: uc_x86_insn = 402;
pub const UC_X86_INS_PHADDW: uc_x86_insn = 403;
pub const UC_X86_INS_PHADDD: uc_x86_insn = 404;
pub const UC_X86_INS_PHSUBD: uc_x86_insn = 405;
pub const UC_X86_INS_PHSUBSW: uc_x86_insn = 406;
pub const UC_X86_INS_PHSUBW: uc_x86_insn = 407;
pub const UC_X86_INS_PINSRW: uc_x86_insn = 408;
pub const UC_X86_INS_PMADDUBSW: uc_x86_insn = 409;
pub const UC_X86_INS_PMADDWD: uc_x86_insn = 410;
pub const UC_X86_INS_PMAXSW: uc_x86_insn = 411;
pub const UC_X86_INS_PMAXUB: uc_x86_insn = 412;
pub const UC_X86_INS_PMINSW: uc_x86_insn = 413;
pub const UC_X86_INS_PMINUB: uc_x86_insn = 414;
pub const UC_X86_INS_PMOVMSKB: uc_x86_insn = 415;
pub const UC_X86_INS_PMULHRSW: uc_x86_insn = 416;
pub const UC_X86_INS_PMULHUW: uc_x86_insn = 417;
pub const UC_X86_INS_PMULHW: uc_x86_insn = 418;
pub const UC_X86_INS_PMULLW: uc_x86_insn = 419;
pub const UC_X86_INS_PMULUDQ: uc_x86_insn = 420;
pub const UC_X86_INS_POR: uc_x86_insn = 421;
pub const UC_X86_INS_PSADBW: uc_x86_insn = 422;
pub const UC_X86_INS_PSHUFB: uc_x86_insn = 423;
pub const UC_X86_INS_PSHUFW: uc_x86_insn = 424;
pub const UC_X86_INS_PSIGNB: uc_x86_insn = 425;
pub const UC_X86_INS_PSIGND: uc_x86_insn = 426;
pub const UC_X86_INS_PSIGNW: uc_x86_insn = 427;
pub const UC_X86_INS_PSLLD: uc_x86_insn = 428;
pub const UC_X86_INS_PSLLQ: uc_x86_insn = 429;
pub const UC_X86_INS_PSLLW: uc_x86_insn = 430;
pub const UC_X86_INS_PSRAD: uc_x86_insn = 431;
pub const UC_X86_INS_PSRAW: uc_x86_insn = 432;
pub const UC_X86_INS_PSRLD: uc_x86_insn = 433;
pub const UC_X86_INS_PSRLQ: uc_x86_insn = 434;
pub const UC_X86_INS_PSRLW: uc_x86_insn = 435;
pub const UC_X86_INS_PSUBB: uc_x86_insn = 436;
pub const UC_X86_INS_PSUBD: uc_x86_insn = 437;
pub const UC_X86_INS_PSUBQ: uc_x86_insn = 438;
pub const UC_X86_INS_PSUBSB: uc_x86_insn = 439;
pub const UC_X86_INS_PSUBSW: uc_x86_insn = 440;
pub const UC_X86_INS_PSUBUSB: uc_x86_insn = 441;
pub const UC_X86_INS_PSUBUSW: uc_x86_insn = 442;
pub const UC_X86_INS_PSUBW: uc_x86_insn = 443;
pub const UC_X86_INS_PUNPCKHBW: uc_x86_insn = 444;
pub const UC_X86_INS_PUNPCKHDQ: uc_x86_insn = 445;
pub const UC_X86_INS_PUNPCKHWD: uc_x86_insn = 446;
pub const UC_X86_INS_PUNPCKLBW: uc_x86_insn = 447;
pub const UC_X86_INS_PUNPCKLDQ: uc_x86_insn = 448;
pub const UC_X86_INS_PUNPCKLWD: uc_x86_insn = 449;
pub const UC_X86_INS_PXOR: uc_x86_insn = 450;
pub const UC_X86_INS_MONITOR: uc_x86_insn = 451;
pub const UC_X86_INS_MONTMUL: uc_x86_insn = 452;
pub const UC_X86_INS_MOV: uc_x86_insn = 453;
pub const UC_X86_INS_MOVABS: uc_x86_insn = 454;
pub const UC_X86_INS_MOVBE: uc_x86_insn = 455;
pub const UC_X86_INS_MOVDDUP: uc_x86_insn = 456;
pub const UC_X86_INS_MOVDQA: uc_x86_insn = 457;
pub const UC_X86_INS_MOVDQU: uc_x86_insn = 458;
pub const UC_X86_INS_MOVHLPS: uc_x86_insn = 459;
pub const UC_X86_INS_MOVHPD: uc_x86_insn = 460;
pub const UC_X86_INS_MOVHPS: uc_x86_insn = 461;
pub const UC_X86_INS_MOVLHPS: uc_x86_insn = 462;
pub const UC_X86_INS_MOVLPD: uc_x86_insn = 463;
pub const UC_X86_INS_MOVLPS: uc_x86_insn = 464;
pub const UC_X86_INS_MOVMSKPD: uc_x86_insn = 465;
pub const UC_X86_INS_MOVMSKPS: uc_x86_insn = 466;
pub const UC_X86_INS_MOVNTDQA: uc_x86_insn = 467;
pub const UC_X86_INS_MOVNTDQ: uc_x86_insn = 468;
pub const UC_X86_INS_MOVNTI: uc_x86_insn = 469;
pub const UC_X86_INS_MOVNTPD: uc_x86_insn = 470;
pub const UC_X86_INS_MOVNTPS: uc_x86_insn = 471;
pub const UC_X86_INS_MOVNTSD: uc_x86_insn = 472;
pub const UC_X86_INS_MOVNTSS: uc_x86_insn = 473;
pub const UC_X86_INS_MOVSB: uc_x86_insn = 474;
pub const UC_X86_INS_MOVSD: uc_x86_insn = 475;
pub const UC_X86_INS_MOVSHDUP: uc_x86_insn = 476;
pub const UC_X86_INS_MOVSLDUP: uc_x86_insn = 477;
pub const UC_X86_INS_MOVSQ: uc_x86_insn = 478;
pub const UC_X86_INS_MOVSS: uc_x86_insn = 479;
pub const UC_X86_INS_MOVSW: uc_x86_insn = 480;
pub const UC_X86_INS_MOVSX: uc_x86_insn = 481;
pub const UC_X86_INS_MOVSXD: uc_x86_insn = 482;
pub const UC_X86_INS_MOVUPD: uc_x86_insn = 483;
pub const UC_X86_INS_MOVUPS: uc_x86_insn = 484;
pub const UC_X86_INS_MOVZX: uc_x86_insn = 485;
pub const UC_X86_INS_MPSADBW: uc_x86_insn = 486;
pub const UC_X86_INS_MUL: uc_x86_insn = 487;
pub const UC_X86_INS_MULPD: uc_x86_insn = 488;
pub const UC_X86_INS_MULPS: uc_x86_insn = 489;
pub const UC_X86_INS_MULSD: uc_x86_insn = 490;
pub const UC_X86_INS_MULSS: uc_x86_insn = 491;
pub const UC_X86_INS_MULX: uc_x86_insn = 492;
pub const UC_X86_INS_FMUL: uc_x86_insn = 493;
pub const UC_X86_INS_FIMUL: uc_x86_insn = 494;
pub const UC_X86_INS_FMULP: uc_x86_insn = 495;
pub const UC_X86_INS_MWAIT: uc_x86_insn = 496;
pub const UC_X86_INS_NEG: uc_x86_insn = 497;
pub const UC_X86_INS_NOP: uc_x86_insn = 498;
pub const UC_X86_INS_NOT: uc_x86_insn = 499;
pub const UC_X86_INS_OUT: uc_x86_insn = 500;
pub const UC_X86_INS_OUTSB: uc_x86_insn = 501;
pub const UC_X86_INS_OUTSD: uc_x86_insn = 502;
pub const UC_X86_INS_OUTSW: uc_x86_insn = 503;
pub const UC_X86_INS_PACKUSDW: uc_x86_insn = 504;
pub const UC_X86_INS_PAUSE: uc_x86_insn = 505;
pub const UC_X86_INS_PAVGUSB: uc_x86_insn = 506;
pub const UC_X86_INS_PBLENDVB: uc_x86_insn = 507;
pub const UC_X86_INS_PBLENDW: uc_x86_insn = 508;
pub const UC_X86_INS_PCLMULQDQ: uc_x86_insn = 509;
pub const UC_X86_INS_PCMPEQQ: uc_x86_insn = 510;
pub const UC_X86_INS_PCMPESTRI: uc_x86_insn = 511;
pub const UC_X86_INS_PCMPESTRM: uc_x86_insn = 512;
pub const UC_X86_INS_PCMPGTQ: uc_x86_insn = 513;
pub const UC_X86_INS_PCMPISTRI: uc_x86_insn = 514;
pub const UC_X86_INS_PCMPISTRM: uc_x86_insn = 515;
pub const UC_X86_INS_PCOMMIT: uc_x86_insn = 516;
pub const UC_X86_INS_PDEP: uc_x86_insn = 517;
pub const UC_X86_INS_PEXT: uc_x86_insn = 518;
pub const UC_X86_INS_PEXTRB: uc_x86_insn = 519;
pub const UC_X86_INS_PEXTRD: uc_x86_insn = 520;
pub const UC_X86_INS_PEXTRQ: uc_x86_insn = 521;
pub const UC_X86_INS_PF2ID: uc_x86_insn = 522;
pub const UC_X86_INS_PF2IW: uc_x86_insn = 523;
pub const UC_X86_INS_PFACC: uc_x86_insn = 524;
pub const UC_X86_INS_PFADD: uc_x86_insn = 525;
pub const UC_X86_INS_PFCMPEQ: uc_x86_insn = 526;
pub const UC_X86_INS_PFCMPGE: uc_x86_insn = 527;
pub const UC_X86_INS_PFCMPGT: uc_x86_insn = 528;
pub const UC_X86_INS_PFMAX: uc_x86_insn = 529;
pub const UC_X86_INS_PFMIN: uc_x86_insn = 530;
pub const UC_X86_INS_PFMUL: uc_x86_insn = 531;
pub const UC_X86_INS_PFNACC: uc_x86_insn = 532;
pub const UC_X86_INS_PFPNACC: uc_x86_insn = 533;
pub const UC_X86_INS_PFRCPIT1: uc_x86_insn = 534;
pub const UC_X86_INS_PFRCPIT2: uc_x86_insn = 535;
pub const UC_X86_INS_PFRCP: uc_x86_insn = 536;
pub const UC_X86_INS_PFRSQIT1: uc_x86_insn = 537;
pub const UC_X86_INS_PFRSQRT: uc_x86_insn = 538;
pub const UC_X86_INS_PFSUBR: uc_x86_insn = 539;
pub const UC_X86_INS_PFSUB: uc_x86_insn = 540;
pub const UC_X86_INS_PHMINPOSUW: uc_x86_insn = 541;
pub const UC_X86_INS_PI2FD: uc_x86_insn = 542;
pub const UC_X86_INS_PI2FW: uc_x86_insn = 543;
pub const UC_X86_INS_PINSRB: uc_x86_insn = 544;
pub const UC_X86_INS_PINSRD: uc_x86_insn = 545;
pub const UC_X86_INS_PINSRQ: uc_x86_insn = 546;
pub const UC_X86_INS_PMAXSB: uc_x86_insn = 547;
pub const UC_X86_INS_PMAXSD: uc_x86_insn = 548;
pub const UC_X86_INS_PMAXUD: uc_x86_insn = 549;
pub const UC_X86_INS_PMAXUW: uc_x86_insn = 550;
pub const UC_X86_INS_PMINSB: uc_x86_insn = 551;
pub const UC_X86_INS_PMINSD: uc_x86_insn = 552;
pub const UC_X86_INS_PMINUD: uc_x86_insn = 553;
pub const UC_X86_INS_PMINUW: uc_x86_insn = 554;
pub const UC_X86_INS_PMOVSXBD: uc_x86_insn = 555;
pub const UC_X86_INS_PMOVSXBQ: uc_x86_insn = 556;
pub const UC_X86_INS_PMOVSXBW: uc_x86_insn = 557;
pub const UC_X86_INS_PMOVSXDQ: uc_x86_insn = 558;
pub const UC_X86_INS_PMOVSXWD: uc_x86_insn = 559;
pub const UC_X86_INS_PMOVSXWQ: uc_x86_insn = 560;
pub const UC_X86_INS_PMOVZXBD: uc_x86_insn = 561;
pub const UC_X86_INS_PMOVZXBQ: uc_x86_insn = 562;
pub const UC_X86_INS_PMOVZXBW: uc_x86_insn = 563;
pub const UC_X86_INS_PMOVZXDQ: uc_x86_insn = 564;
pub const UC_X86_INS_PMOVZXWD: uc_x86_insn = 565;
pub const UC_X86_INS_PMOVZXWQ: uc_x86_insn = 566;
pub const UC_X86_INS_PMULDQ: uc_x86_insn = 567;
pub const UC_X86_INS_PMULHRW: uc_x86_insn = 568;
pub const UC_X86_INS_PMULLD: uc_x86_insn = 569;
pub const UC_X86_INS_POP: uc_x86_insn = 570;
pub const UC_X86_INS_POPAW: uc_x86_insn = 571;
pub const UC_X86_INS_POPAL: uc_x86_insn = 572;
pub const UC_X86_INS_POPCNT: uc_x86_insn = 573;
pub const UC_X86_INS_POPF: uc_x86_insn = 574;
pub const UC_X86_INS_POPFD: uc_x86_insn = 575;
pub const UC_X86_INS_POPFQ: uc_x86_insn = 576;
pub const UC_X86_INS_PREFETCH: uc_x86_insn = 577;
pub const UC_X86_INS_PREFETCHNTA: uc_x86_insn = 578;
pub const UC_X86_INS_PREFETCHT0: uc_x86_insn = 579;
pub const UC_X86_INS_PREFETCHT1: uc_x86_insn = 580;
pub const UC_X86_INS_PREFETCHT2: uc_x86_insn = 581;
pub const UC_X86_INS_PREFETCHW: uc_x86_insn = 582;
pub const UC_X86_INS_PSHUFD: uc_x86_insn = 583;
pub const UC_X86_INS_PSHUFHW: uc_x86_insn = 584;
pub const UC_X86_INS_PSHUFLW: uc_x86_insn = 585;
pub const UC_X86_INS_PSLLDQ: uc_x86_insn = 586;
pub const UC_X86_INS_PSRLDQ: uc_x86_insn = 587;
pub const UC_X86_INS_PSWAPD: uc_x86_insn = 588;
pub const UC_X86_INS_PTEST: uc_x86_insn = 589;
pub const UC_X86_INS_PUNPCKHQDQ: uc_x86_insn = 590;
pub const UC_X86_INS_PUNPCKLQDQ: uc_x86_insn = 591;
pub const UC_X86_INS_PUSH: uc_x86_insn = 592;
pub const UC_X86_INS_PUSHAW: uc_x86_insn = 593;
pub const UC_X86_INS_PUSHAL: uc_x86_insn = 594;
pub const UC_X86_INS_PUSHF: uc_x86_insn = 595;
pub const UC_X86_INS_PUSHFD: uc_x86_insn = 596;
pub const UC_X86_INS_PUSHFQ: uc_x86_insn = 597;
pub const UC_X86_INS_RCL: uc_x86_insn = 598;
pub const UC_X86_INS_RCPPS: uc_x86_insn = 599;
pub const UC_X86_INS_RCPSS: uc_x86_insn = 600;
pub const UC_X86_INS_RCR: uc_x86_insn = 601;
pub const UC_X86_INS_RDFSBASE: uc_x86_insn = 602;
pub const UC_X86_INS_RDGSBASE: uc_x86_insn = 603;
pub const UC_X86_INS_RDMSR: uc_x86_insn = 604;
pub const UC_X86_INS_RDPMC: uc_x86_insn = 605;
pub const UC_X86_INS_RDRAND: uc_x86_insn = 606;
pub const UC_X86_INS_RDSEED: uc_x86_insn = 607;
pub const UC_X86_INS_RDTSC: uc_x86_insn = 608;
pub const UC_X86_INS_RDTSCP: uc_x86_insn = 609;
pub const UC_X86_INS_ROL: uc_x86_insn = 610;
pub const UC_X86_INS_ROR: uc_x86_insn = 611;
pub const UC_X86_INS_RORX: uc_x86_insn = 612;
pub const UC_X86_INS_ROUNDPD: uc_x86_insn = 613;
pub const UC_X86_INS_ROUNDPS: uc_x86_insn = 614;
pub const UC_X86_INS_ROUNDSD: uc_x86_insn = 615;
pub const UC_X86_INS_ROUNDSS: uc_x86_insn = 616;
pub const UC_X86_INS_RSM: uc_x86_insn = 617;
pub const UC_X86_INS_RSQRTPS: uc_x86_insn = 618;
pub const UC_X86_INS_RSQRTSS: uc_x86_insn = 619;
pub const UC_X86_INS_SAHF: uc_x86_insn = 620;
pub const UC_X86_INS_SAL: uc_x86_insn = 621;
pub const UC_X86_INS_SALC: uc_x86_insn = 622;
pub const UC_X86_INS_SAR: uc_x86_insn = 623;
pub const UC_X86_INS_SARX: uc_x86_insn = 624;
pub const UC_X86_INS_SBB: uc_x86_insn = 625;
pub const UC_X86_INS_SCASB: uc_x86_insn = 626;
pub const UC_X86_INS_SCASD: uc_x86_insn = 627;
pub const UC_X86_INS_SCASQ: uc_x86_insn = 628;
pub const UC_X86_INS_SCASW: uc_x86_insn = 629;
pub const UC_X86_INS_SETAE: uc_x86_insn = 630;
pub const UC_X86_INS_SETA: uc_x86_insn = 631;
pub const UC_X86_INS_SETBE: uc_x86_insn = 632;
pub const UC_X86_INS_SETB: uc_x86_insn = 633;
pub const UC_X86_INS_SETE: uc_x86_insn = 634;
pub const UC_X86_INS_SETGE: uc_x86_insn = 635;
pub const UC_X86_INS_SETG: uc_x86_insn = 636;
pub const UC_X86_INS_SETLE: uc_x86_insn = 637;
pub const UC_X86_INS_SETL: uc_x86_insn = 638;
pub const UC_X86_INS_SETNE: uc_x86_insn = 639;
pub const UC_X86_INS_SETNO: uc_x86_insn = 640;
pub const UC_X86_INS_SETNP: uc_x86_insn = 641;
pub const UC_X86_INS_SETNS: uc_x86_insn = 642;
pub const UC_X86_INS_SETO: uc_x86_insn = 643;
pub const UC_X86_INS_SETP: uc_x86_insn = 644;
pub const UC_X86_INS_SETS: uc_x86_insn = 645;
pub const UC_X86_INS_SFENCE: uc_x86_insn = 646;
pub const UC_X86_INS_SGDT: uc_x86_insn = 647;
pub const UC_X86_INS_SHA1MSG1: uc_x86_insn = 648;
pub const UC_X86_INS_SHA1MSG2: uc_x86_insn = 649;
pub const UC_X86_INS_SHA1NEXTE: uc_x86_insn = 650;
pub const UC_X86_INS_SHA1RNDS4: uc_x86_insn = 651;
pub const UC_X86_INS_SHA256MSG1: uc_x86_insn = 652;
pub const UC_X86_INS_SHA256MSG2: uc_x86_insn = 653;
pub const UC_X86_INS_SHA256RNDS2: uc_x86_insn = 654;
pub const UC_X86_INS_SHL: uc_x86_insn = 655;
pub const UC_X86_INS_SHLD: uc_x86_insn = 656;
pub const UC_X86_INS_SHLX: uc_x86_insn = 657;
pub const UC_X86_INS_SHR: uc_x86_insn = 658;
pub const UC_X86_INS_SHRD: uc_x86_insn = 659;
pub const UC_X86_INS_SHRX: uc_x86_insn = 660;
pub const UC_X86_INS_SHUFPD: uc_x86_insn = 661;
pub const UC_X86_INS_SHUFPS: uc_x86_insn = 662;
pub const UC_X86_INS_SIDT: uc_x86_insn = 663;
pub const UC_X86_INS_FSIN: uc_x86_insn = 664;
pub const UC_X86_INS_SKINIT: uc_x86_insn = 665;
pub const UC_X86_INS_SLDT: uc_x86_insn = 666;
pub const UC_X86_INS_SMSW: uc_x86_insn = 667;
pub const UC_X86_INS_SQRTPD: uc_x86_insn = 668;
pub const UC_X86_INS_SQRTPS: uc_x86_insn = 669;
pub const UC_X86_INS_SQRTSD: uc_x86_insn = 670;
pub const UC_X86_INS_SQRTSS: uc_x86_insn = 671;
pub const UC_X86_INS_FSQRT: uc_x86_insn = 672;
pub const UC_X86_INS_STAC: uc_x86_insn = 673;
pub const UC_X86_INS_STC: uc_x86_insn = 674;
pub const UC_X86_INS_STD: uc_x86_insn = 675;
pub const UC_X86_INS_STGI: uc_x86_insn = 676;
pub const UC_X86_INS_STI: uc_x86_insn = 677;
pub const UC_X86_INS_STMXCSR: uc_x86_insn = 678;
pub const UC_X86_INS_STOSB: uc_x86_insn = 679;
pub const UC_X86_INS_STOSD: uc_x86_insn = 680;
pub const UC_X86_INS_STOSQ: uc_x86_insn = 681;
pub const UC_X86_INS_STOSW: uc_x86_insn = 682;
pub const UC_X86_INS_STR: uc_x86_insn = 683;
pub const UC_X86_INS_FST: uc_x86_insn = 684;
pub const UC_X86_INS_FSTP: uc_x86_insn = 685;
pub const UC_X86_INS_FSTPNCE: uc_x86_insn = 686;
pub const UC_X86_INS_FXCH: uc_x86_insn = 687;
pub const UC_X86_INS_SUBPD: uc_x86_insn = 688;
pub const UC_X86_INS_SUBPS: uc_x86_insn = 689;
pub const UC_X86_INS_FSUBR: uc_x86_insn = 690;
pub const UC_X86_INS_FISUBR: uc_x86_insn = 691;
pub const UC_X86_INS_FSUBRP: uc_x86_insn = 692;
pub const UC_X86_INS_SUBSD: uc_x86_insn = 693;
pub const UC_X86_INS_SUBSS: uc_x86_insn = 694;
pub const UC_X86_INS_FSUB: uc_x86_insn = 695;
pub const UC_X86_INS_FISUB: uc_x86_insn = 696;
pub const UC_X86_INS_FSUBP: uc_x86_insn = 697;
pub const UC_X86_INS_SWAPGS: uc_x86_insn = 698;
pub const UC_X86_INS_SYSCALL: uc_x86_insn = 699;
pub const UC_X86_INS_SYSENTER: uc_x86_insn = 700;
pub const UC_X86_INS_SYSEXIT: uc_x86_insn = 701;
pub const UC_X86_INS_SYSRET: uc_x86_insn = 702;
pub const UC_X86_INS_T1MSKC: uc_x86_insn = 703;
pub const UC_X86_INS_TEST: uc_x86_insn = 704;
pub const UC_X86_INS_UD2: uc_x86_insn = 705;
pub const UC_X86_INS_FTST: uc_x86_insn = 706;
pub const UC_X86_INS_TZCNT: uc_x86_insn = 707;
pub const UC_X86_INS_TZMSK: uc_x86_insn = 708;
pub const UC_X86_INS_FUCOMPI: uc_x86_insn = 709;
pub const UC_X86_INS_FUCOMI: uc_x86_insn = 710;
pub const UC_X86_INS_FUCOMPP: uc_x86_insn = 711;
pub const UC_X86_INS_FUCOMP: uc_x86_insn = 712;
pub const UC_X86_INS_FUCOM: uc_x86_insn = 713;
pub const UC_X86_INS_UD2B: uc_x86_insn = 714;
pub const UC_X86_INS_UNPCKHPD: uc_x86_insn = 715;
pub const UC_X86_INS_UNPCKHPS: uc_x86_insn = 716;
pub const UC_X86_INS_UNPCKLPD: uc_x86_insn = 717;
pub const UC_X86_INS_UNPCKLPS: uc_x86_insn = 718;
pub const UC_X86_INS_VADDPD: uc_x86_insn = 719;
pub const UC_X86_INS_VADDPS: uc_x86_insn = 720;
pub const UC_X86_INS_VADDSD: uc_x86_insn = 721;
pub const UC_X86_INS_VADDSS: uc_x86_insn = 722;
pub const UC_X86_INS_VADDSUBPD: uc_x86_insn = 723;
pub const UC_X86_INS_VADDSUBPS: uc_x86_insn = 724;
pub const UC_X86_INS_VAESDECLAST: uc_x86_insn = 725;
pub const UC_X86_INS_VAESDEC: uc_x86_insn = 726;
pub const UC_X86_INS_VAESENCLAST: uc_x86_insn = 727;
pub const UC_X86_INS_VAESENC: uc_x86_insn = 728;
pub const UC_X86_INS_VAESIMC: uc_x86_insn = 729;
pub const UC_X86_INS_VAESKEYGENASSIST: uc_x86_insn = 730;
pub const UC_X86_INS_VALIGND: uc_x86_insn = 731;
pub const UC_X86_INS_VALIGNQ: uc_x86_insn = 732;
pub const UC_X86_INS_VANDNPD: uc_x86_insn = 733;
pub const UC_X86_INS_VANDNPS: uc_x86_insn = 734;
pub const UC_X86_INS_VANDPD: uc_x86_insn = 735;
pub const UC_X86_INS_VANDPS: uc_x86_insn = 736;
pub const UC_X86_INS_VBLENDMPD: uc_x86_insn = 737;
pub const UC_X86_INS_VBLENDMPS: uc_x86_insn = 738;
pub const UC_X86_INS_VBLENDPD: uc_x86_insn = 739;
pub const UC_X86_INS_VBLENDPS: uc_x86_insn = 740;
pub const UC_X86_INS_VBLENDVPD: uc_x86_insn = 741;
pub const UC_X86_INS_VBLENDVPS: uc_x86_insn = 742;
pub const UC_X86_INS_VBROADCASTF128: uc_x86_insn = 743;
pub const UC_X86_INS_VBROADCASTI32X4: uc_x86_insn = 744;
pub const UC_X86_INS_VBROADCASTI64X4: uc_x86_insn = 745;
pub const UC_X86_INS_VBROADCASTSD: uc_x86_insn = 746;
pub const UC_X86_INS_VBROADCASTSS: uc_x86_insn = 747;
pub const UC_X86_INS_VCMPPD: uc_x86_insn = 748;
pub const UC_X86_INS_VCMPPS: uc_x86_insn = 749;
pub const UC_X86_INS_VCMPSD: uc_x86_insn = 750;
pub const UC_X86_INS_VCMPSS: uc_x86_insn = 751;
pub const UC_X86_INS_VCOMPRESSPD: uc_x86_insn = 752;
pub const UC_X86_INS_VCOMPRESSPS: uc_x86_insn = 753;
pub const UC_X86_INS_VCVTDQ2PD: uc_x86_insn = 754;
pub const UC_X86_INS_VCVTDQ2PS: uc_x86_insn = 755;
pub const UC_X86_INS_VCVTPD2DQX: uc_x86_insn = 756;
pub const UC_X86_INS_VCVTPD2DQ: uc_x86_insn = 757;
pub const UC_X86_INS_VCVTPD2PSX: uc_x86_insn = 758;
pub const UC_X86_INS_VCVTPD2PS: uc_x86_insn = 759;
pub const UC_X86_INS_VCVTPD2UDQ: uc_x86_insn = 760;
pub const UC_X86_INS_VCVTPH2PS: uc_x86_insn = 761;
pub const UC_X86_INS_VCVTPS2DQ: uc_x86_insn = 762;
pub const UC_X86_INS_VCVTPS2PD: uc_x86_insn = 763;
pub const UC_X86_INS_VCVTPS2PH: uc_x86_insn = 764;
pub const UC_X86_INS_VCVTPS2UDQ: uc_x86_insn = 765;
pub const UC_X86_INS_VCVTSD2SI: uc_x86_insn = 766;
pub const UC_X86_INS_VCVTSD2USI: uc_x86_insn = 767;
pub const UC_X86_INS_VCVTSS2SI: uc_x86_insn = 768;
pub const UC_X86_INS_VCVTSS2USI: uc_x86_insn = 769;
pub const UC_X86_INS_VCVTTPD2DQX: uc_x86_insn = 770;
pub const UC_X86_INS_VCVTTPD2DQ: uc_x86_insn = 771;
pub const UC_X86_INS_VCVTTPD2UDQ: uc_x86_insn = 772;
pub const UC_X86_INS_VCVTTPS2DQ: uc_x86_insn = 773;
pub const UC_X86_INS_VCVTTPS2UDQ: uc_x86_insn = 774;
pub const UC_X86_INS_VCVTUDQ2PD: uc_x86_insn = 775;
pub const UC_X86_INS_VCVTUDQ2PS: uc_x86_insn = 776;
pub const UC_X86_INS_VDIVPD: uc_x86_insn = 777;
pub const UC_X86_INS_VDIVPS: uc_x86_insn = 778;
pub const UC_X86_INS_VDIVSD: uc_x86_insn = 779;
pub const UC_X86_INS_VDIVSS: uc_x86_insn = 780;
pub const UC_X86_INS_VDPPD: uc_x86_insn = 781;
pub const UC_X86_INS_VDPPS: uc_x86_insn = 782;
pub const UC_X86_INS_VERR: uc_x86_insn = 783;
pub const UC_X86_INS_VERW: uc_x86_insn = 784;
pub const UC_X86_INS_VEXP2PD: uc_x86_insn = 785;
pub const UC_X86_INS_VEXP2PS: uc_x86_insn = 786;
pub const UC_X86_INS_VEXPANDPD: uc_x86_insn = 787;
pub const UC_X86_INS_VEXPANDPS: uc_x86_insn = 788;
pub const UC_X86_INS_VEXTRACTF128: uc_x86_insn = 789;
pub const UC_X86_INS_VEXTRACTF32X4: uc_x86_insn = 790;
pub const UC_X86_INS_VEXTRACTF64X4: uc_x86_insn = 791;
pub const UC_X86_INS_VEXTRACTI128: uc_x86_insn = 792;
pub const UC_X86_INS_VEXTRACTI32X4: uc_x86_insn = 793;
pub const UC_X86_INS_VEXTRACTI64X4: uc_x86_insn = 794;
pub const UC_X86_INS_VEXTRACTPS: uc_x86_insn = 795;
pub const UC_X86_INS_VFMADD132PD: uc_x86_insn = 796;
pub const UC_X86_INS_VFMADD132PS: uc_x86_insn = 797;
pub const UC_X86_INS_VFMADDPD: uc_x86_insn = 798;
pub const UC_X86_INS_VFMADD213PD: uc_x86_insn = 799;
pub const UC_X86_INS_VFMADD231PD: uc_x86_insn = 800;
pub const UC_X86_INS_VFMADDPS: uc_x86_insn = 801;
pub const UC_X86_INS_VFMADD213PS: uc_x86_insn = 802;
pub const UC_X86_INS_VFMADD231PS: uc_x86_insn = 803;
pub const UC_X86_INS_VFMADDSD: uc_x86_insn = 804;
pub const UC_X86_INS_VFMADD213SD: uc_x86_insn = 805;
pub const UC_X86_INS_VFMADD132SD: uc_x86_insn = 806;
pub const UC_X86_INS_VFMADD231SD: uc_x86_insn = 807;
pub const UC_X86_INS_VFMADDSS: uc_x86_insn = 808;
pub const UC_X86_INS_VFMADD213SS: uc_x86_insn = 809;
pub const UC_X86_INS_VFMADD132SS: uc_x86_insn = 810;
pub const UC_X86_INS_VFMADD231SS: uc_x86_insn = 811;
pub const UC_X86_INS_VFMADDSUB132PD: uc_x86_insn = 812;
pub const UC_X86_INS_VFMADDSUB132PS: uc_x86_insn = 813;
pub const UC_X86_INS_VFMADDSUBPD: uc_x86_insn = 814;
pub const UC_X86_INS_VFMADDSUB213PD: uc_x86_insn = 815;
pub const UC_X86_INS_VFMADDSUB231PD: uc_x86_insn = 816;
pub const UC_X86_INS_VFMADDSUBPS: uc_x86_insn = 817;
pub const UC_X86_INS_VFMADDSUB213PS: uc_x86_insn = 818;
pub const UC_X86_INS_VFMADDSUB231PS: uc_x86_insn = 819;
pub const UC_X86_INS_VFMSUB132PD: uc_x86_insn = 820;
pub const UC_X86_INS_VFMSUB132PS: uc_x86_insn = 821;
pub const UC_X86_INS_VFMSUBADD132PD: uc_x86_insn = 822;
pub const UC_X86_INS_VFMSUBADD132PS: uc_x86_insn = 823;
pub const UC_X86_INS_VFMSUBADDPD: uc_x86_insn = 824;
pub const UC_X86_INS_VFMSUBADD213PD: uc_x86_insn = 825;
pub const UC_X86_INS_VFMSUBADD231PD: uc_x86_insn = 826;
pub const UC_X86_INS_VFMSUBADDPS: uc_x86_insn = 827;
pub const UC_X86_INS_VFMSUBADD213PS: uc_x86_insn = 828;
pub const UC_X86_INS_VFMSUBADD231PS: uc_x86_insn = 829;
pub const UC_X86_INS_VFMSUBPD: uc_x86_insn = 830;
pub const UC_X86_INS_VFMSUB213PD: uc_x86_insn = 831;
pub const UC_X86_INS_VFMSUB231PD: uc_x86_insn = 832;
pub const UC_X86_INS_VFMSUBPS: uc_x86_insn = 833;
pub const UC_X86_INS_VFMSUB213PS: uc_x86_insn = 834;
pub const UC_X86_INS_VFMSUB231PS: uc_x86_insn = 835;
pub const UC_X86_INS_VFMSUBSD: uc_x86_insn = 836;
pub const UC_X86_INS_VFMSUB213SD: uc_x86_insn = 837;
pub const UC_X86_INS_VFMSUB132SD: uc_x86_insn = 838;
pub const UC_X86_INS_VFMSUB231SD: uc_x86_insn = 839;
pub const UC_X86_INS_VFMSUBSS: uc_x86_insn = 840;
pub const UC_X86_INS_VFMSUB213SS: uc_x86_insn = 841;
pub const UC_X86_INS_VFMSUB132SS: uc_x86_insn = 842;
pub const UC_X86_INS_VFMSUB231SS: uc_x86_insn = 843;
pub const UC_X86_INS_VFNMADD132PD: uc_x86_insn = 844;
pub const UC_X86_INS_VFNMADD132PS: uc_x86_insn = 845;
pub const UC_X86_INS_VFNMADDPD: uc_x86_insn = 846;
pub const UC_X86_INS_VFNMADD213PD: uc_x86_insn = 847;
pub const UC_X86_INS_VFNMADD231PD: uc_x86_insn = 848;
pub const UC_X86_INS_VFNMADDPS: uc_x86_insn = 849;
pub const UC_X86_INS_VFNMADD213PS: uc_x86_insn = 850;
pub const UC_X86_INS_VFNMADD231PS: uc_x86_insn = 851;
pub const UC_X86_INS_VFNMADDSD: uc_x86_insn = 852;
pub const UC_X86_INS_VFNMADD213SD: uc_x86_insn = 853;
pub const UC_X86_INS_VFNMADD132SD: uc_x86_insn = 854;
pub const UC_X86_INS_VFNMADD231SD: uc_x86_insn = 855;
pub const UC_X86_INS_VFNMADDSS: uc_x86_insn = 856;
pub const UC_X86_INS_VFNMADD213SS: uc_x86_insn = 857;
pub const UC_X86_INS_VFNMADD132SS: uc_x86_insn = 858;
pub const UC_X86_INS_VFNMADD231SS: uc_x86_insn = 859;
pub const UC_X86_INS_VFNMSUB132PD: uc_x86_insn = 860;
pub const UC_X86_INS_VFNMSUB132PS: uc_x86_insn = 861;
pub const UC_X86_INS_VFNMSUBPD: uc_x86_insn = 862;
pub const UC_X86_INS_VFNMSUB213PD: uc_x86_insn = 863;
pub const UC_X86_INS_VFNMSUB231PD: uc_x86_insn = 864;
pub const UC_X86_INS_VFNMSUBPS: uc_x86_insn = 865;
pub const UC_X86_INS_VFNMSUB213PS: uc_x86_insn = 866;
pub const UC_X86_INS_VFNMSUB231PS: uc_x86_insn = 867;
pub const UC_X86_INS_VFNMSUBSD: uc_x86_insn = 868;
pub const UC_X86_INS_VFNMSUB213SD: uc_x86_insn = 869;
pub const UC_X86_INS_VFNMSUB132SD: uc_x86_insn = 870;
pub const UC_X86_INS_VFNMSUB231SD: uc_x86_insn = 871;
pub const UC_X86_INS_VFNMSUBSS: uc_x86_insn = 872;
pub const UC_X86_INS_VFNMSUB213SS: uc_x86_insn = 873;
pub const UC_X86_INS_VFNMSUB132SS: uc_x86_insn = 874;
pub const UC_X86_INS_VFNMSUB231SS: uc_x86_insn = 875;
pub const UC_X86_INS_VFRCZPD: uc_x86_insn = 876;
pub const UC_X86_INS_VFRCZPS: uc_x86_insn = 877;
pub const UC_X86_INS_VFRCZSD: uc_x86_insn = 878;
pub const UC_X86_INS_VFRCZSS: uc_x86_insn = 879;
pub const UC_X86_INS_VORPD: uc_x86_insn = 880;
pub const UC_X86_INS_VORPS: uc_x86_insn = 881;
pub const UC_X86_INS_VXORPD: uc_x86_insn = 882;
pub const UC_X86_INS_VXORPS: uc_x86_insn = 883;
pub const UC_X86_INS_VGATHERDPD: uc_x86_insn = 884;
pub const UC_X86_INS_VGATHERDPS: uc_x86_insn = 885;
pub const UC_X86_INS_VGATHERPF0DPD: uc_x86_insn = 886;
pub const UC_X86_INS_VGATHERPF0DPS: uc_x86_insn = 887;
pub const UC_X86_INS_VGATHERPF0QPD: uc_x86_insn = 888;
pub const UC_X86_INS_VGATHERPF0QPS: uc_x86_insn = 889;
pub const UC_X86_INS_VGATHERPF1DPD: uc_x86_insn = 890;
pub const UC_X86_INS_VGATHERPF1DPS: uc_x86_insn = 891;
pub const UC_X86_INS_VGATHERPF1QPD: uc_x86_insn = 892;
pub const UC_X86_INS_VGATHERPF1QPS: uc_x86_insn = 893;
pub const UC_X86_INS_VGATHERQPD: uc_x86_insn = 894;
pub const UC_X86_INS_VGATHERQPS: uc_x86_insn = 895;
pub const UC_X86_INS_VHADDPD: uc_x86_insn = 896;
pub const UC_X86_INS_VHADDPS: uc_x86_insn = 897;
pub const UC_X86_INS_VHSUBPD: uc_x86_insn = 898;
pub const UC_X86_INS_VHSUBPS: uc_x86_insn = 899;
pub const UC_X86_INS_VINSERTF128: uc_x86_insn = 900;
pub const UC_X86_INS_VINSERTF32X4: uc_x86_insn = 901;
pub const UC_X86_INS_VINSERTF32X8: uc_x86_insn = 902;
pub const UC_X86_INS_VINSERTF64X2: uc_x86_insn = 903;
pub const UC_X86_INS_VINSERTF64X4: uc_x86_insn = 904;
pub const UC_X86_INS_VINSERTI128: uc_x86_insn = 905;
pub const UC_X86_INS_VINSERTI32X4: uc_x86_insn = 906;
pub const UC_X86_INS_VINSERTI32X8: uc_x86_insn = 907;
pub const UC_X86_INS_VINSERTI64X2: uc_x86_insn = 908;
pub const UC_X86_INS_VINSERTI64X4: uc_x86_insn = 909;
pub const UC_X86_INS_VINSERTPS: uc_x86_insn = 910;
pub const UC_X86_INS_VLDDQU: uc_x86_insn = 911;
pub const UC_X86_INS_VLDMXCSR: uc_x86_insn = 912;
pub const UC_X86_INS_VMASKMOVDQU: uc_x86_insn = 913;
pub const UC_X86_INS_VMASKMOVPD: uc_x86_insn = 914;
pub const UC_X86_INS_VMASKMOVPS: uc_x86_insn = 915;
pub const UC_X86_INS_VMAXPD: uc_x86_insn = 916;
pub const UC_X86_INS_VMAXPS: uc_x86_insn = 917;
pub const UC_X86_INS_VMAXSD: uc_x86_insn = 918;
pub const UC_X86_INS_VMAXSS: uc_x86_insn = 919;
pub const UC_X86_INS_VMCALL: uc_x86_insn = 920;
pub const UC_X86_INS_VMCLEAR: uc_x86_insn = 921;
pub const UC_X86_INS_VMFUNC: uc_x86_insn = 922;
pub const UC_X86_INS_VMINPD: uc_x86_insn = 923;
pub const UC_X86_INS_VMINPS: uc_x86_insn = 924;
pub const UC_X86_INS_VMINSD: uc_x86_insn = 925;
pub const UC_X86_INS_VMINSS: uc_x86_insn = 926;
pub const UC_X86_INS_VMLAUNCH: uc_x86_insn = 927;
pub const UC_X86_INS_VMLOAD: uc_x86_insn = 928;
pub const UC_X86_INS_VMMCALL: uc_x86_insn = 929;
pub const UC_X86_INS_VMOVQ: uc_x86_insn = 930;
pub const UC_X86_INS_VMOVDDUP: uc_x86_insn = 931;
pub const UC_X86_INS_VMOVD: uc_x86_insn = 932;
pub const UC_X86_INS_VMOVDQA32: uc_x86_insn = 933;
pub const UC_X86_INS_VMOVDQA64: uc_x86_insn = 934;
pub const UC_X86_INS_VMOVDQA: uc_x86_insn = 935;
pub const UC_X86_INS_VMOVDQU16: uc_x86_insn = 936;
pub const UC_X86_INS_VMOVDQU32: uc_x86_insn = 937;
pub const UC_X86_INS_VMOVDQU64: uc_x86_insn = 938;
pub const UC_X86_INS_VMOVDQU8: uc_x86_insn = 939;
pub const UC_X86_INS_VMOVDQU: uc_x86_insn = 940;
pub const UC_X86_INS_VMOVHLPS: uc_x86_insn = 941;
pub const UC_X86_INS_VMOVHPD: uc_x86_insn = 942;
pub const UC_X86_INS_VMOVHPS: uc_x86_insn = 943;
pub const UC_X86_INS_VMOVLHPS: uc_x86_insn = 944;
pub const UC_X86_INS_VMOVLPD: uc_x86_insn = 945;
pub const UC_X86_INS_VMOVLPS: uc_x86_insn = 946;
pub const UC_X86_INS_VMOVMSKPD: uc_x86_insn = 947;
pub const UC_X86_INS_VMOVMSKPS: uc_x86_insn = 948;
pub const UC_X86_INS_VMOVNTDQA: uc_x86_insn = 949;
pub const UC_X86_INS_VMOVNTDQ: uc_x86_insn = 950;
pub const UC_X86_INS_VMOVNTPD: uc_x86_insn = 951;
pub const UC_X86_INS_VMOVNTPS: uc_x86_insn = 952;
pub const UC_X86_INS_VMOVSD: uc_x86_insn = 953;
pub const UC_X86_INS_VMOVSHDUP: uc_x86_insn = 954;
pub const UC_X86_INS_VMOVSLDUP: uc_x86_insn = 955;
pub const UC_X86_INS_VMOVSS: uc_x86_insn = 956;
pub const UC_X86_INS_VMOVUPD: uc_x86_insn = 957;
pub const UC_X86_INS_VMOVUPS: uc_x86_insn = 958;
pub const UC_X86_INS_VMPSADBW: uc_x86_insn = 959;
pub const UC_X86_INS_VMPTRLD: uc_x86_insn = 960;
pub const UC_X86_INS_VMPTRST: uc_x86_insn = 961;
pub const UC_X86_INS_VMREAD: uc_x86_insn = 962;
pub const UC_X86_INS_VMRESUME: uc_x86_insn = 963;
pub const UC_X86_INS_VMRUN: uc_x86_insn = 964;
pub const UC_X86_INS_VMSAVE: uc_x86_insn = 965;
pub const UC_X86_INS_VMULPD: uc_x86_insn = 966;
pub const UC_X86_INS_VMULPS: uc_x86_insn = 967;
pub const UC_X86_INS_VMULSD: uc_x86_insn = 968;
pub const UC_X86_INS_VMULSS: uc_x86_insn = 969;
pub const UC_X86_INS_VMWRITE: uc_x86_insn = 970;
pub const UC_X86_INS_VMXOFF: uc_x86_insn = 971;
pub const UC_X86_INS_VMXON: uc_x86_insn = 972;
pub const UC_X86_INS_VPABSB: uc_x86_insn = 973;
pub const UC_X86_INS_VPABSD: uc_x86_insn = 974;
pub const UC_X86_INS_VPABSQ: uc_x86_insn = 975;
pub const UC_X86_INS_VPABSW: uc_x86_insn = 976;
pub const UC_X86_INS_VPACKSSDW: uc_x86_insn = 977;
pub const UC_X86_INS_VPACKSSWB: uc_x86_insn = 978;
pub const UC_X86_INS_VPACKUSDW: uc_x86_insn = 979;
pub const UC_X86_INS_VPACKUSWB: uc_x86_insn = 980;
pub const UC_X86_INS_VPADDB: uc_x86_insn = 981;
pub const UC_X86_INS_VPADDD: uc_x86_insn = 982;
pub const UC_X86_INS_VPADDQ: uc_x86_insn = 983;
pub const UC_X86_INS_VPADDSB: uc_x86_insn = 984;
pub const UC_X86_INS_VPADDSW: uc_x86_insn = 985;
pub const UC_X86_INS_VPADDUSB: uc_x86_insn = 986;
pub const UC_X86_INS_VPADDUSW: uc_x86_insn = 987;
pub const UC_X86_INS_VPADDW: uc_x86_insn = 988;
pub const UC_X86_INS_VPALIGNR: uc_x86_insn = 989;
pub const UC_X86_INS_VPANDD: uc_x86_insn = 990;
pub const UC_X86_INS_VPANDND: uc_x86_insn = 991;
pub const UC_X86_INS_VPANDNQ: uc_x86_insn = 992;
pub const UC_X86_INS_VPANDN: uc_x86_insn = 993;
pub const UC_X86_INS_VPANDQ: uc_x86_insn = 994;
pub const UC_X86_INS_VPAND: uc_x86_insn = 995;
pub const UC_X86_INS_VPAVGB: uc_x86_insn = 996;
pub const UC_X86_INS_VPAVGW: uc_x86_insn = 997;
pub const UC_X86_INS_VPBLENDD: uc_x86_insn = 998;
pub const UC_X86_INS_VPBLENDMB: uc_x86_insn = 999;
pub const UC_X86_INS_VPBLENDMD: uc_x86_insn = 1000;
pub const UC_X86_INS_VPBLENDMQ: uc_x86_insn = 1001;
pub const UC_X86_INS_VPBLENDMW: uc_x86_insn = 1002;
pub const UC_X86_INS_VPBLENDVB: uc_x86_insn = 1003;
pub const UC_X86_INS_VPBLENDW: uc_x86_insn = 1004;
pub const UC_X86_INS_VPBROADCASTB: uc_x86_insn = 1005;
pub const UC_X86_INS_VPBROADCASTD: uc_x86_insn = 1006;
pub const UC_X86_INS_VPBROADCASTMB2Q: uc_x86_insn = 1007;
pub const UC_X86_INS_VPBROADCASTMW2D: uc_x86_insn = 1008;
pub const UC_X86_INS_VPBROADCASTQ: uc_x86_insn = 1009;
pub const UC_X86_INS_VPBROADCASTW: uc_x86_insn = 1010;
pub const UC_X86_INS_VPCLMULQDQ: uc_x86_insn = 1011;
pub const UC_X86_INS_VPCMOV: uc_x86_insn = 1012;
pub const UC_X86_INS_VPCMPB: uc_x86_insn = 1013;
pub const UC_X86_INS_VPCMPD: uc_x86_insn = 1014;
pub const UC_X86_INS_VPCMPEQB: uc_x86_insn = 1015;
pub const UC_X86_INS_VPCMPEQD: uc_x86_insn = 1016;
pub const UC_X86_INS_VPCMPEQQ: uc_x86_insn = 1017;
pub const UC_X86_INS_VPCMPEQW: uc_x86_insn = 1018;
pub const UC_X86_INS_VPCMPESTRI: uc_x86_insn = 1019;
pub const UC_X86_INS_VPCMPESTRM: uc_x86_insn = 1020;
pub const UC_X86_INS_VPCMPGTB: uc_x86_insn = 1021;
pub const UC_X86_INS_VPCMPGTD: uc_x86_insn = 1022;
pub const UC_X86_INS_VPCMPGTQ: uc_x86_insn = 1023;
pub const UC_X86_INS_VPCMPGTW: uc_x86_insn = 1024;
pub const UC_X86_INS_VPCMPISTRI: uc_x86_insn = 1025;
pub const UC_X86_INS_VPCMPISTRM: uc_x86_insn = 1026;
pub const UC_X86_INS_VPCMPQ: uc_x86_insn = 1027;
pub const UC_X86_INS_VPCMPUB: uc_x86_insn = 1028;
pub const UC_X86_INS_VPCMPUD: uc_x86_insn = 1029;
pub const UC_X86_INS_VPCMPUQ: uc_x86_insn = 1030;
pub const UC_X86_INS_VPCMPUW: uc_x86_insn = 1031;
pub const UC_X86_INS_VPCMPW: uc_x86_insn = 1032;
pub const UC_X86_INS_VPCOMB: uc_x86_insn = 1033;
pub const UC_X86_INS_VPCOMD: uc_x86_insn = 1034;
pub const UC_X86_INS_VPCOMPRESSD: uc_x86_insn = 1035;
pub const UC_X86_INS_VPCOMPRESSQ: uc_x86_insn = 1036;
pub const UC_X86_INS_VPCOMQ: uc_x86_insn = 1037;
pub const UC_X86_INS_VPCOMUB: uc_x86_insn = 1038;
pub const UC_X86_INS_VPCOMUD: uc_x86_insn = 1039;
pub const UC_X86_INS_VPCOMUQ: uc_x86_insn = 1040;
pub const UC_X86_INS_VPCOMUW: uc_x86_insn = 1041;
pub const UC_X86_INS_VPCOMW: uc_x86_insn = 1042;
pub const UC_X86_INS_VPCONFLICTD: uc_x86_insn = 1043;
pub const UC_X86_INS_VPCONFLICTQ: uc_x86_insn = 1044;
pub const UC_X86_INS_VPERM2F128: uc_x86_insn = 1045;
pub const UC_X86_INS_VPERM2I128: uc_x86_insn = 1046;
pub const UC_X86_INS_VPERMD: uc_x86_insn = 1047;
pub const UC_X86_INS_VPERMI2D: uc_x86_insn = 1048;
pub const UC_X86_INS_VPERMI2PD: uc_x86_insn = 1049;
pub const UC_X86_INS_VPERMI2PS: uc_x86_insn = 1050;
pub const UC_X86_INS_VPERMI2Q: uc_x86_insn = 1051;
pub const UC_X86_INS_VPERMIL2PD: uc_x86_insn = 1052;
pub const UC_X86_INS_VPERMIL2PS: uc_x86_insn = 1053;
pub const UC_X86_INS_VPERMILPD: uc_x86_insn = 1054;
pub const UC_X86_INS_VPERMILPS: uc_x86_insn = 1055;
pub const UC_X86_INS_VPERMPD: uc_x86_insn = 1056;
pub const UC_X86_INS_VPERMPS: uc_x86_insn = 1057;
pub const UC_X86_INS_VPERMQ: uc_x86_insn = 1058;
pub const UC_X86_INS_VPERMT2D: uc_x86_insn = 1059;
pub const UC_X86_INS_VPERMT2PD: uc_x86_insn = 1060;
pub const UC_X86_INS_VPERMT2PS: uc_x86_insn = 1061;
pub const UC_X86_INS_VPERMT2Q: uc_x86_insn = 1062;
pub const UC_X86_INS_VPEXPANDD: uc_x86_insn = 1063;
pub const UC_X86_INS_VPEXPANDQ: uc_x86_insn = 1064;
pub const UC_X86_INS_VPEXTRB: uc_x86_insn = 1065;
pub const UC_X86_INS_VPEXTRD: uc_x86_insn = 1066;
pub const UC_X86_INS_VPEXTRQ: uc_x86_insn = 1067;
pub const UC_X86_INS_VPEXTRW: uc_x86_insn = 1068;
pub const UC_X86_INS_VPGATHERDD: uc_x86_insn = 1069;
pub const UC_X86_INS_VPGATHERDQ: uc_x86_insn = 1070;
pub const UC_X86_INS_VPGATHERQD: uc_x86_insn = 1071;
pub const UC_X86_INS_VPGATHERQQ: uc_x86_insn = 1072;
pub const UC_X86_INS_VPHADDBD: uc_x86_insn = 1073;
pub const UC_X86_INS_VPHADDBQ: uc_x86_insn = 1074;
pub const UC_X86_INS_VPHADDBW: uc_x86_insn = 1075;
pub const UC_X86_INS_VPHADDDQ: uc_x86_insn = 1076;
pub const UC_X86_INS_VPHADDD: uc_x86_insn = 1077;
pub const UC_X86_INS_VPHADDSW: uc_x86_insn = 1078;
pub const UC_X86_INS_VPHADDUBD: uc_x86_insn = 1079;
pub const UC_X86_INS_VPHADDUBQ: uc_x86_insn = 1080;
pub const UC_X86_INS_VPHADDUBW: uc_x86_insn = 1081;
pub const UC_X86_INS_VPHADDUDQ: uc_x86_insn = 1082;
pub const UC_X86_INS_VPHADDUWD: uc_x86_insn = 1083;
pub const UC_X86_INS_VPHADDUWQ: uc_x86_insn = 1084;
pub const UC_X86_INS_VPHADDWD: uc_x86_insn = 1085;
pub const UC_X86_INS_VPHADDWQ: uc_x86_insn = 1086;
pub const UC_X86_INS_VPHADDW: uc_x86_insn = 1087;
pub const UC_X86_INS_VPHMINPOSUW: uc_x86_insn = 1088;
pub const UC_X86_INS_VPHSUBBW: uc_x86_insn = 1089;
pub const UC_X86_INS_VPHSUBDQ: uc_x86_insn = 1090;
pub const UC_X86_INS_VPHSUBD: uc_x86_insn = 1091;
pub const UC_X86_INS_VPHSUBSW: uc_x86_insn = 1092;
pub const UC_X86_INS_VPHSUBWD: uc_x86_insn = 1093;
pub const UC_X86_INS_VPHSUBW: uc_x86_insn = 1094;
pub const UC_X86_INS_VPINSRB: uc_x86_insn = 1095;
pub const UC_X86_INS_VPINSRD: uc_x86_insn = 1096;
pub const UC_X86_INS_VPINSRQ: uc_x86_insn = 1097;
pub const UC_X86_INS_VPINSRW: uc_x86_insn = 1098;
pub const UC_X86_INS_VPLZCNTD: uc_x86_insn = 1099;
pub const UC_X86_INS_VPLZCNTQ: uc_x86_insn = 1100;
pub const UC_X86_INS_VPMACSDD: uc_x86_insn = 1101;
pub const UC_X86_INS_VPMACSDQH: uc_x86_insn = 1102;
pub const UC_X86_INS_VPMACSDQL: uc_x86_insn = 1103;
pub const UC_X86_INS_VPMACSSDD: uc_x86_insn = 1104;
pub const UC_X86_INS_VPMACSSDQH: uc_x86_insn = 1105;
pub const UC_X86_INS_VPMACSSDQL: uc_x86_insn = 1106;
pub const UC_X86_INS_VPMACSSWD: uc_x86_insn = 1107;
pub const UC_X86_INS_VPMACSSWW: uc_x86_insn = 1108;
pub const UC_X86_INS_VPMACSWD: uc_x86_insn = 1109;
pub const UC_X86_INS_VPMACSWW: uc_x86_insn = 1110;
pub const UC_X86_INS_VPMADCSSWD: uc_x86_insn = 1111;
pub const UC_X86_INS_VPMADCSWD: uc_x86_insn = 1112;
pub const UC_X86_INS_VPMADDUBSW: uc_x86_insn = 1113;
pub const UC_X86_INS_VPMADDWD: uc_x86_insn = 1114;
pub const UC_X86_INS_VPMASKMOVD: uc_x86_insn = 1115;
pub const UC_X86_INS_VPMASKMOVQ: uc_x86_insn = 1116;
pub const UC_X86_INS_VPMAXSB: uc_x86_insn = 1117;
pub const UC_X86_INS_VPMAXSD: uc_x86_insn = 1118;
pub const UC_X86_INS_VPMAXSQ: uc_x86_insn = 1119;
pub const UC_X86_INS_VPMAXSW: uc_x86_insn = 1120;
pub const UC_X86_INS_VPMAXUB: uc_x86_insn = 1121;
pub const UC_X86_INS_VPMAXUD: uc_x86_insn = 1122;
pub const UC_X86_INS_VPMAXUQ: uc_x86_insn = 1123;
pub const UC_X86_INS_VPMAXUW: uc_x86_insn = 1124;
pub const UC_X86_INS_VPMINSB: uc_x86_insn = 1125;
pub const UC_X86_INS_VPMINSD: uc_x86_insn = 1126;
pub const UC_X86_INS_VPMINSQ: uc_x86_insn = 1127;
pub const UC_X86_INS_VPMINSW: uc_x86_insn = 1128;
pub const UC_X86_INS_VPMINUB: uc_x86_insn = 1129;
pub const UC_X86_INS_VPMINUD: uc_x86_insn = 1130;
pub const UC_X86_INS_VPMINUQ: uc_x86_insn = 1131;
pub const UC_X86_INS_VPMINUW: uc_x86_insn = 1132;
pub const UC_X86_INS_VPMOVDB: uc_x86_insn = 1133;
pub const UC_X86_INS_VPMOVDW: uc_x86_insn = 1134;
pub const UC_X86_INS_VPMOVM2B: uc_x86_insn = 1135;
pub const UC_X86_INS_VPMOVM2D: uc_x86_insn = 1136;
pub const UC_X86_INS_VPMOVM2Q: uc_x86_insn = 1137;
pub const UC_X86_INS_VPMOVM2W: uc_x86_insn = 1138;
pub const UC_X86_INS_VPMOVMSKB: uc_x86_insn = 1139;
pub const UC_X86_INS_VPMOVQB: uc_x86_insn = 1140;
pub const UC_X86_INS_VPMOVQD: uc_x86_insn = 1141;
pub const UC_X86_INS_VPMOVQW: uc_x86_insn = 1142;
pub const UC_X86_INS_VPMOVSDB: uc_x86_insn = 1143;
pub const UC_X86_INS_VPMOVSDW: uc_x86_insn = 1144;
pub const UC_X86_INS_VPMOVSQB: uc_x86_insn = 1145;
pub const UC_X86_INS_VPMOVSQD: uc_x86_insn = 1146;
pub const UC_X86_INS_VPMOVSQW: uc_x86_insn = 1147;
pub const UC_X86_INS_VPMOVSXBD: uc_x86_insn = 1148;
pub const UC_X86_INS_VPMOVSXBQ: uc_x86_insn = 1149;
pub const UC_X86_INS_VPMOVSXBW: uc_x86_insn = 1150;
pub const UC_X86_INS_VPMOVSXDQ: uc_x86_insn = 1151;
pub const UC_X86_INS_VPMOVSXWD: uc_x86_insn = 1152;
pub const UC_X86_INS_VPMOVSXWQ: uc_x86_insn = 1153;
pub const UC_X86_INS_VPMOVUSDB: uc_x86_insn = 1154;
pub const UC_X86_INS_VPMOVUSDW: uc_x86_insn = 1155;
pub const UC_X86_INS_VPMOVUSQB: uc_x86_insn = 1156;
pub const UC_X86_INS_VPMOVUSQD: uc_x86_insn = 1157;
pub const UC_X86_INS_VPMOVUSQW: uc_x86_insn = 1158;
pub const UC_X86_INS_VPMOVZXBD: uc_x86_insn = 1159;
pub const UC_X86_INS_VPMOVZXBQ: uc_x86_insn = 1160;
pub const UC_X86_INS_VPMOVZXBW: uc_x86_insn = 1161;
pub const UC_X86_INS_VPMOVZXDQ: uc_x86_insn = 1162;
pub const UC_X86_INS_VPMOVZXWD: uc_x86_insn = 1163;
pub const UC_X86_INS_VPMOVZXWQ: uc_x86_insn = 1164;
pub const UC_X86_INS_VPMULDQ: uc_x86_insn = 1165;
pub const UC_X86_INS_VPMULHRSW: uc_x86_insn = 1166;
pub const UC_X86_INS_VPMULHUW: uc_x86_insn = 1167;
pub const UC_X86_INS_VPMULHW: uc_x86_insn = 1168;
pub const UC_X86_INS_VPMULLD: uc_x86_insn = 1169;
pub const UC_X86_INS_VPMULLQ: uc_x86_insn = 1170;
pub const UC_X86_INS_VPMULLW: uc_x86_insn = 1171;
pub const UC_X86_INS_VPMULUDQ: uc_x86_insn = 1172;
pub const UC_X86_INS_VPORD: uc_x86_insn = 1173;
pub const UC_X86_INS_VPORQ: uc_x86_insn = 1174;
pub const UC_X86_INS_VPOR: uc_x86_insn = 1175;
pub const UC_X86_INS_VPPERM: uc_x86_insn = 1176;
pub const UC_X86_INS_VPROTB: uc_x86_insn = 1177;
pub const UC_X86_INS_VPROTD: uc_x86_insn = 1178;
pub const UC_X86_INS_VPROTQ: uc_x86_insn = 1179;
pub const UC_X86_INS_VPROTW: uc_x86_insn = 1180;
pub const UC_X86_INS_VPSADBW: uc_x86_insn = 1181;
pub const UC_X86_INS_VPSCATTERDD: uc_x86_insn = 1182;
pub const UC_X86_INS_VPSCATTERDQ: uc_x86_insn = 1183;
pub const UC_X86_INS_VPSCATTERQD: uc_x86_insn = 1184;
pub const UC_X86_INS_VPSCATTERQQ: uc_x86_insn = 1185;
pub const UC_X86_INS_VPSHAB: uc_x86_insn = 1186;
pub const UC_X86_INS_VPSHAD: uc_x86_insn = 1187;
pub const UC_X86_INS_VPSHAQ: uc_x86_insn = 1188;
pub const UC_X86_INS_VPSHAW: uc_x86_insn = 1189;
pub const UC_X86_INS_VPSHLB: uc_x86_insn = 1190;
pub const UC_X86_INS_VPSHLD: uc_x86_insn = 1191;
pub const UC_X86_INS_VPSHLQ: uc_x86_insn = 1192;
pub const UC_X86_INS_VPSHLW: uc_x86_insn = 1193;
pub const UC_X86_INS_VPSHUFB: uc_x86_insn = 1194;
pub const UC_X86_INS_VPSHUFD: uc_x86_insn = 1195;
pub const UC_X86_INS_VPSHUFHW: uc_x86_insn = 1196;
pub const UC_X86_INS_VPSHUFLW: uc_x86_insn = 1197;
pub const UC_X86_INS_VPSIGNB: uc_x86_insn = 1198;
pub const UC_X86_INS_VPSIGND: uc_x86_insn = 1199;
pub const UC_X86_INS_VPSIGNW: uc_x86_insn = 1200;
pub const UC_X86_INS_VPSLLDQ: uc_x86_insn = 1201;
pub const UC_X86_INS_VPSLLD: uc_x86_insn = 1202;
pub const UC_X86_INS_VPSLLQ: uc_x86_insn = 1203;
pub const UC_X86_INS_VPSLLVD: uc_x86_insn = 1204;
pub const UC_X86_INS_VPSLLVQ: uc_x86_insn = 1205;
pub const UC_X86_INS_VPSLLW: uc_x86_insn = 1206;
pub const UC_X86_INS_VPSRAD: uc_x86_insn = 1207;
pub const UC_X86_INS_VPSRAQ: uc_x86_insn = 1208;
pub const UC_X86_INS_VPSRAVD: uc_x86_insn = 1209;
pub const UC_X86_INS_VPSRAVQ: uc_x86_insn = 1210;
pub const UC_X86_INS_VPSRAW: uc_x86_insn = 1211;
pub const UC_X86_INS_VPSRLDQ: uc_x86_insn = 1212;
pub const UC_X86_INS_VPSRLD: uc_x86_insn = 1213;
pub const UC_X86_INS_VPSRLQ: uc_x86_insn = 1214;
pub const UC_X86_INS_VPSRLVD: uc_x86_insn = 1215;
pub const UC_X86_INS_VPSRLVQ: uc_x86_insn = 1216;
pub const UC_X86_INS_VPSRLW: uc_x86_insn = 1217;
pub const UC_X86_INS_VPSUBB: uc_x86_insn = 1218;
pub const UC_X86_INS_VPSUBD: uc_x86_insn = 1219;
pub const UC_X86_INS_VPSUBQ: uc_x86_insn = 1220;
pub const UC_X86_INS_VPSUBSB: uc_x86_insn = 1221;
pub const UC_X86_INS_VPSUBSW: uc_x86_insn = 1222;
pub const UC_X86_INS_VPSUBUSB: uc_x86_insn = 1223;
pub const UC_X86_INS_VPSUBUSW: uc_x86_insn = 1224;
pub const UC_X86_INS_VPSUBW: uc_x86_insn = 1225;
pub const UC_X86_INS_VPTESTMD: uc_x86_insn = 1226;
pub const UC_X86_INS_VPTESTMQ: uc_x86_insn = 1227;
pub const UC_X86_INS_VPTESTNMD: uc_x86_insn = 1228;
pub const UC_X86_INS_VPTESTNMQ: uc_x86_insn = 1229;
pub const UC_X86_INS_VPTEST: uc_x86_insn = 1230;
pub const UC_X86_INS_VPUNPCKHBW: uc_x86_insn = 1231;
pub const UC_X86_INS_VPUNPCKHDQ: uc_x86_insn = 1232;
pub const UC_X86_INS_VPUNPCKHQDQ: uc_x86_insn = 1233;
pub const UC_X86_INS_VPUNPCKHWD: uc_x86_insn = 1234;
pub const UC_X86_INS_VPUNPCKLBW: uc_x86_insn = 1235;
pub const UC_X86_INS_VPUNPCKLDQ: uc_x86_insn = 1236;
pub const UC_X86_INS_VPUNPCKLQDQ: uc_x86_insn = 1237;
pub const UC_X86_INS_VPUNPCKLWD: uc_x86_insn = 1238;
pub const UC_X86_INS_VPXORD: uc_x86_insn = 1239;
pub const UC_X86_INS_VPXORQ: uc_x86_insn = 1240;
pub const UC_X86_INS_VPXOR: uc_x86_insn = 1241;
pub const UC_X86_INS_VRCP14PD: uc_x86_insn = 1242;
pub const UC_X86_INS_VRCP14PS: uc_x86_insn = 1243;
pub const UC_X86_INS_VRCP14SD: uc_x86_insn = 1244;
pub const UC_X86_INS_VRCP14SS: uc_x86_insn = 1245;
pub const UC_X86_INS_VRCP28PD: uc_x86_insn = 1246;
pub const UC_X86_INS_VRCP28PS: uc_x86_insn = 1247;
pub const UC_X86_INS_VRCP28SD: uc_x86_insn = 1248;
pub const UC_X86_INS_VRCP28SS: uc_x86_insn = 1249;
pub const UC_X86_INS_VRCPPS: uc_x86_insn = 1250;
pub const UC_X86_INS_VRCPSS: uc_x86_insn = 1251;
pub const UC_X86_INS_VRNDSCALEPD: uc_x86_insn = 1252;
pub const UC_X86_INS_VRNDSCALEPS: uc_x86_insn = 1253;
pub const UC_X86_INS_VRNDSCALESD: uc_x86_insn = 1254;
pub const UC_X86_INS_VRNDSCALESS: uc_x86_insn = 1255;
pub const UC_X86_INS_VROUNDPD: uc_x86_insn = 1256;
pub const UC_X86_INS_VROUNDPS: uc_x86_insn = 1257;
pub const UC_X86_INS_VROUNDSD: uc_x86_insn = 1258;
pub const UC_X86_INS_VROUNDSS: uc_x86_insn = 1259;
pub const UC_X86_INS_VRSQRT14PD: uc_x86_insn = 1260;
pub const UC_X86_INS_VRSQRT14PS: uc_x86_insn = 1261;
pub const UC_X86_INS_VRSQRT14SD: uc_x86_insn = 1262;
pub const UC_X86_INS_VRSQRT14SS: uc_x86_insn = 1263;
pub const UC_X86_INS_VRSQRT28PD: uc_x86_insn = 1264;
pub const UC_X86_INS_VRSQRT28PS: uc_x86_insn = 1265;
pub const UC_X86_INS_VRSQRT28SD: uc_x86_insn = 1266;
pub const UC_X86_INS_VRSQRT28SS: uc_x86_insn = 1267;
pub const UC_X86_INS_VRSQRTPS: uc_x86_insn = 1268;
pub const UC_X86_INS_VRSQRTSS: uc_x86_insn = 1269;
pub const UC_X86_INS_VSCATTERDPD: uc_x86_insn = 1270;
pub const UC_X86_INS_VSCATTERDPS: uc_x86_insn = 1271;
pub const UC_X86_INS_VSCATTERPF0DPD: uc_x86_insn = 1272;
pub const UC_X86_INS_VSCATTERPF0DPS: uc_x86_insn = 1273;
pub const UC_X86_INS_VSCATTERPF0QPD: uc_x86_insn = 1274;
pub const UC_X86_INS_VSCATTERPF0QPS: uc_x86_insn = 1275;
pub const UC_X86_INS_VSCATTERPF1DPD: uc_x86_insn = 1276;
pub const UC_X86_INS_VSCATTERPF1DPS: uc_x86_insn = 1277;
pub const UC_X86_INS_VSCATTERPF1QPD: uc_x86_insn = 1278;
pub const UC_X86_INS_VSCATTERPF1QPS: uc_x86_insn = 1279;
pub const UC_X86_INS_VSCATTERQPD: uc_x86_insn = 1280;
pub const UC_X86_INS_VSCATTERQPS: uc_x86_insn = 1281;
pub const UC_X86_INS_VSHUFPD: uc_x86_insn = 1282;
pub const UC_X86_INS_VSHUFPS: uc_x86_insn = 1283;
pub const UC_X86_INS_VSQRTPD: uc_x86_insn = 1284;
pub const UC_X86_INS_VSQRTPS: uc_x86_insn = 1285;
pub const UC_X86_INS_VSQRTSD: uc_x86_insn = 1286;
pub const UC_X86_INS_VSQRTSS: uc_x86_insn = 1287;
pub const UC_X86_INS_VSTMXCSR: uc_x86_insn = 1288;
pub const UC_X86_INS_VSUBPD: uc_x86_insn = 1289;
pub const UC_X86_INS_VSUBPS: uc_x86_insn = 1290;
pub const UC_X86_INS_VSUBSD: uc_x86_insn = 1291;
pub const UC_X86_INS_VSUBSS: uc_x86_insn = 1292;
pub const UC_X86_INS_VTESTPD: uc_x86_insn = 1293;
pub const UC_X86_INS_VTESTPS: uc_x86_insn = 1294;
pub const UC_X86_INS_VUNPCKHPD: uc_x86_insn = 1295;
pub const UC_X86_INS_VUNPCKHPS: uc_x86_insn = 1296;
pub const UC_X86_INS_VUNPCKLPD: uc_x86_insn = 1297;
pub const UC_X86_INS_VUNPCKLPS: uc_x86_insn = 1298;
pub const UC_X86_INS_VZEROALL: uc_x86_insn = 1299;
pub const UC_X86_INS_VZEROUPPER: uc_x86_insn = 1300;
pub const UC_X86_INS_WAIT: uc_x86_insn = 1301;
pub const UC_X86_INS_WBINVD: uc_x86_insn = 1302;
pub const UC_X86_INS_WRFSBASE: uc_x86_insn = 1303;
pub const UC_X86_INS_WRGSBASE: uc_x86_insn = 1304;
pub const UC_X86_INS_WRMSR: uc_x86_insn = 1305;
pub const UC_X86_INS_XABORT: uc_x86_insn = 1306;
pub const UC_X86_INS_XACQUIRE: uc_x86_insn = 1307;
pub const UC_X86_INS_XBEGIN: uc_x86_insn = 1308;
pub const UC_X86_INS_XCHG: uc_x86_insn = 1309;
pub const UC_X86_INS_XCRYPTCBC: uc_x86_insn = 1310;
pub const UC_X86_INS_XCRYPTCFB: uc_x86_insn = 1311;
pub const UC_X86_INS_XCRYPTCTR: uc_x86_insn = 1312;
pub const UC_X86_INS_XCRYPTECB: uc_x86_insn = 1313;
pub const UC_X86_INS_XCRYPTOFB: uc_x86_insn = 1314;
pub const UC_X86_INS_XEND: uc_x86_insn = 1315;
pub const UC_X86_INS_XGETBV: uc_x86_insn = 1316;
pub const UC_X86_INS_XLATB: uc_x86_insn = 1317;
pub const UC_X86_INS_XRELEASE: uc_x86_insn = 1318;
pub const UC_X86_INS_XRSTOR: uc_x86_insn = 1319;
pub const UC_X86_INS_XRSTOR64: uc_x86_insn = 1320;
pub const UC_X86_INS_XRSTORS: uc_x86_insn = 1321;
pub const UC_X86_INS_XRSTORS64: uc_x86_insn = 1322;
pub const UC_X86_INS_XSAVE: uc_x86_insn = 1323;
pub const UC_X86_INS_XSAVE64: uc_x86_insn = 1324;
pub const UC_X86_INS_XSAVEC: uc_x86_insn = 1325;
pub const UC_X86_INS_XSAVEC64: uc_x86_insn = 1326;
pub const UC_X86_INS_XSAVEOPT: uc_x86_insn = 1327;
pub const UC_X86_INS_XSAVEOPT64: uc_x86_insn = 1328;
pub const UC_X86_INS_XSAVES: uc_x86_insn = 1329;
pub const UC_X86_INS_XSAVES64: uc_x86_insn = 1330;
pub const UC_X86_INS_XSETBV: uc_x86_insn = 1331;
pub const UC_X86_INS_XSHA1: uc_x86_insn = 1332;
pub const UC_X86_INS_XSHA256: uc_x86_insn = 1333;
pub const UC_X86_INS_XSTORE: uc_x86_insn = 1334;
pub const UC_X86_INS_XTEST: uc_x86_insn = 1335;
pub const UC_X86_INS_FDISI8087_NOP: uc_x86_insn = 1336;
pub const UC_X86_INS_FENI8087_NOP: uc_x86_insn = 1337;
pub const UC_X86_INS_ENDING: uc_x86_insn = 1338;
pub type uc_x86_insn = ::std::os::raw::c_int;
pub const UC_ARCH_ARM: uc_arch = 1;
pub const UC_ARCH_ARM64: uc_arch = 2;
pub const UC_ARCH_MIPS: uc_arch = 3;
pub const UC_ARCH_X86: uc_arch = 4;
pub const UC_ARCH_PPC: uc_arch = 5;
pub const UC_ARCH_SPARC: uc_arch = 6;
pub const UC_ARCH_M68K: uc_arch = 7;
pub const UC_ARCH_RISCV: uc_arch = 8;
pub const UC_ARCH_MAX: uc_arch = 9;
pub type uc_arch = ::std::os::raw::c_int;
pub const UC_MODE_LITTLE_ENDIAN: uc_mode = 0;
pub const UC_MODE_BIG_ENDIAN: uc_mode = 1073741824;
pub const UC_MODE_ARM: uc_mode = 0;
pub const UC_MODE_THUMB: uc_mode = 16;
pub const UC_MODE_MCLASS: uc_mode = 32;
pub const UC_MODE_V8: uc_mode = 64;
pub const UC_MODE_ARM926: uc_mode = 128;
pub const UC_MODE_ARM946: uc_mode = 256;
pub const UC_MODE_ARM1176: uc_mode = 512;
pub const UC_MODE_MICRO: uc_mode = 16;
pub const UC_MODE_MIPS3: uc_mode = 32;
pub const UC_MODE_MIPS32R6: uc_mode = 64;
pub const UC_MODE_MIPS32: uc_mode = 4;
pub const UC_MODE_MIPS64: uc_mode = 8;
pub const UC_MODE_16: uc_mode = 2;
pub const UC_MODE_32: uc_mode = 4;
pub const UC_MODE_64: uc_mode = 8;
pub const UC_MODE_PPC32: uc_mode = 4;
pub const UC_MODE_PPC64: uc_mode = 8;
pub const UC_MODE_QPX: uc_mode = 16;
pub const UC_MODE_SPARC32: uc_mode = 4;
pub const UC_MODE_SPARC64: uc_mode = 8;
pub const UC_MODE_V9: uc_mode = 16;
pub const UC_MODE_RISCV32: uc_mode = 4;
pub const UC_MODE_RISCV64: uc_mode = 8;
pub type uc_mode = ::std::os::raw::c_int;
pub const UC_ERR_OK: uc_err = 0;
pub const UC_ERR_NOMEM: uc_err = 1;
pub const UC_ERR_ARCH: uc_err = 2;
pub const UC_ERR_HANDLE: uc_err = 3;
pub const UC_ERR_MODE: uc_err = 4;
pub const UC_ERR_VERSION: uc_err = 5;
pub const UC_ERR_READ_UNMAPPED: uc_err = 6;
pub const UC_ERR_WRITE_UNMAPPED: uc_err = 7;
pub const UC_ERR_FETCH_UNMAPPED: uc_err = 8;
pub const UC_ERR_HOOK: uc_err = 9;
pub const UC_ERR_INSN_INVALID: uc_err = 10;
pub const UC_ERR_MAP: uc_err = 11;
pub const UC_ERR_WRITE_PROT: uc_err = 12;
pub const UC_ERR_READ_PROT: uc_err = 13;
pub const UC_ERR_FETCH_PROT: uc_err = 14;
pub const UC_ERR_ARG: uc_err = 15;
pub const UC_ERR_READ_UNALIGNED: uc_err = 16;
pub const UC_ERR_WRITE_UNALIGNED: uc_err = 17;
pub const UC_ERR_FETCH_UNALIGNED: uc_err = 18;
pub const UC_ERR_HOOK_EXIST: uc_err = 19;
pub const UC_ERR_RESOURCE: uc_err = 20;
pub const UC_ERR_EXCEPTION: uc_err = 21;
pub type uc_err = ::std::os::raw::c_int;
pub type uc_cb_hookcode_t = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        address: u64,
        size: u32,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
pub type uc_cb_hookintr_t = ::core::option::Option<
    unsafe extern "C" fn(uc: *mut uc_engine, intno: u32, user_data: *mut ::core::ffi::c_void),
>;
pub type uc_cb_hookinsn_invalid_t = ::core::option::Option<
    unsafe extern "C" fn(uc: *mut uc_engine, user_data: *mut ::core::ffi::c_void) -> bool,
>;
pub type uc_cb_insn_in_t = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        port: u32,
        size: ::std::os::raw::c_int,
        user_data: *mut ::core::ffi::c_void,
    ) -> u32,
>;
pub type uc_cb_insn_out_t = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        port: u32,
        size: ::std::os::raw::c_int,
        value: u32,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uc_tb {
    pub pc: u64,
    pub icount: u16,
    pub size: u16,
}
pub type uc_hook_edge_gen_t = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        cur_tb: *mut uc_tb,
        prev_tb: *mut uc_tb,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
pub type uc_hook_tcg_op_2 = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        address: u64,
        arg1: u64,
        arg2: u64,
        size: u32,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
pub type uc_hook_tcg_sub_t = uc_hook_tcg_op_2;
pub type uc_cb_mmio_read_t = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        offset: u64,
        size: ::std::os::raw::c_uint,
        user_data: *mut ::core::ffi::c_void,
    ) -> u64,
>;
pub type uc_cb_mmio_write_t = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        offset: u64,
        size: ::std::os::raw::c_uint,
        value: u64,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
pub const UC_MEM_READ: uc_mem_type = 16;
pub const UC_MEM_WRITE: uc_mem_type = 17;
pub const UC_MEM_FETCH: uc_mem_type = 18;
pub const UC_MEM_READ_UNMAPPED: uc_mem_type = 19;
pub const UC_MEM_WRITE_UNMAPPED: uc_mem_type = 20;
pub const UC_MEM_FETCH_UNMAPPED: uc_mem_type = 21;
pub const UC_MEM_WRITE_PROT: uc_mem_type = 22;
pub const UC_MEM_READ_PROT: uc_mem_type = 23;
pub const UC_MEM_FETCH_PROT: uc_mem_type = 24;
pub const UC_MEM_READ_AFTER: uc_mem_type = 25;
pub type uc_mem_type = ::std::os::raw::c_int;
pub const UC_TCG_OP_SUB: uc_tcg_op_code = 0;
pub type uc_tcg_op_code = ::std::os::raw::c_int;
pub const UC_TCG_OP_FLAG_CMP: uc_tcg_op_flag = 1;
pub const UC_TCG_OP_FLAG_DIRECT: uc_tcg_op_flag = 2;
pub type uc_tcg_op_flag = ::std::os::raw::c_int;
pub const UC_HOOK_INTR: uc_hook_type = 1;
pub const UC_HOOK_INSN: uc_hook_type = 2;
pub const UC_HOOK_CODE: uc_hook_type = 4;
pub const UC_HOOK_BLOCK: uc_hook_type = 8;
pub const UC_HOOK_MEM_READ_UNMAPPED: uc_hook_type = 16;
pub const UC_HOOK_MEM_WRITE_UNMAPPED: uc_hook_type = 32;
pub const UC_HOOK_MEM_FETCH_UNMAPPED: uc_hook_type = 64;
pub const UC_HOOK_MEM_READ_PROT: uc_hook_type = 128;
pub const UC_HOOK_MEM_WRITE_PROT: uc_hook_type = 256;
pub const UC_HOOK_MEM_FETCH_PROT: uc_hook_type = 512;
pub const UC_HOOK_MEM_READ: uc_hook_type = 1024;
pub const UC_HOOK_MEM_WRITE: uc_hook_type = 2048;
pub const UC_HOOK_MEM_FETCH: uc_hook_type = 4096;
pub const UC_HOOK_MEM_READ_AFTER: uc_hook_type = 8192;
pub const UC_HOOK_INSN_INVALID: uc_hook_type = 16384;
pub const UC_HOOK_EDGE_GENERATED: uc_hook_type = 32768;
pub const UC_HOOK_TCG_OPCODE: uc_hook_type = 65536;
pub type uc_hook_type = ::std::os::raw::c_int;
pub type uc_cb_hookmem_t = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        type_: uc_mem_type,
        address: u64,
        size: ::std::os::raw::c_int,
        value: i64,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
pub type uc_cb_eventmem_t = ::core::option::Option<
    unsafe extern "C" fn(
        uc: *mut uc_engine,
        type_: uc_mem_type,
        address: u64,
        size: ::std::os::raw::c_int,
        value: i64,
        user_data: *mut ::core::ffi::c_void,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uc_mem_region {
    pub begin: u64,
    pub end: u64,
    pub perms: u32,
}
pub const UC_QUERY_MODE: uc_query_type = 1;
pub const UC_QUERY_PAGE_SIZE: uc_query_type = 2;
pub const UC_QUERY_ARCH: uc_query_type = 3;
pub const UC_QUERY_TIMEOUT: uc_query_type = 4;
pub type uc_query_type = ::std::os::raw::c_int;
pub const UC_CTL_UC_MODE: uc_control_type = 0;
pub const UC_CTL_UC_PAGE_SIZE: uc_control_type = 1;
pub const UC_CTL_UC_ARCH: uc_control_type = 2;
pub const UC_CTL_UC_TIMEOUT: uc_control_type = 3;
pub const UC_CTL_UC_USE_EXITS: uc_control_type = 4;
pub const UC_CTL_UC_EXITS_CNT: uc_control_type = 5;
pub const UC_CTL_UC_EXITS: uc_control_type = 6;
pub const UC_CTL_CPU_MODEL: uc_control_type = 7;
pub const UC_CTL_TB_REQUEST_CACHE: uc_control_type = 8;
pub const UC_CTL_TB_REMOVE_CACHE: uc_control_type = 9;
pub type uc_control_type = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug)]
pub struct uc_context {
    _unused: [u8; 0],
}
extern "C" {
    pub fn uc_version(
        major: *mut ::std::os::raw::c_uint,
        minor: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn uc_arch_supported(arch: uc_arch) -> bool;
}
extern "C" {
    pub fn uc_open(arch: uc_arch, mode: uc_mode, uc: *mut *mut uc_engine) -> uc_err;
}
extern "C" {
    pub fn uc_close(uc: *mut uc_engine) -> uc_err;
}
extern "C" {
    pub fn uc_query(uc: *mut uc_engine, type_: uc_query_type, result: *mut usize) -> uc_err;
}
extern "C" {
    pub fn uc_ctl(uc: *mut uc_engine, control: uc_control_type, ...) -> uc_err;
}
extern "C" {
    pub fn uc_errno(uc: *mut uc_engine) -> uc_err;
}
extern "C" {
    pub fn uc_strerror(code: uc_err) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn uc_reg_write(
        uc: *mut uc_engine,
        regid: ::std::os::raw::c_int,
        value: *const ::core::ffi::c_void,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_reg_read(
        uc: *mut uc_engine,
        regid: ::std::os::raw::c_int,
        value: *mut ::core::ffi::c_void,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_reg_write_batch(
        uc: *mut uc_engine,
        regs: *mut ::std::os::raw::c_int,
        vals: *const *mut ::core::ffi::c_void,
        count: ::std::os::raw::c_int,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_reg_read_batch(
        uc: *mut uc_engine,
        regs: *mut ::std::os::raw::c_int,
        vals: *mut *mut ::core::ffi::c_void,
        count: ::std::os::raw::c_int,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_mem_write(
        uc: *mut uc_engine,
        address: u64,
        bytes: *const ::core::ffi::c_void,
        size: usize,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_mem_read(
        uc: *mut uc_engine,
        address: u64,
        bytes: *mut ::core::ffi::c_void,
        size: usize,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_emu_start(
        uc: *mut uc_engine,
        begin: u64,
        until: u64,
        timeout: u64,
        count: usize,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_emu_stop(uc: *mut uc_engine) -> uc_err;
}
extern "C" {
    pub fn uc_hook_add(
        uc: *mut uc_engine,
        hh: *mut uc_hook,
        type_: ::std::os::raw::c_int,
        callback: *mut ::core::ffi::c_void,
        user_data: *mut ::core::ffi::c_void,
        begin: u64,
        end: u64,
        ...
    ) -> uc_err;
}
extern "C" {
    pub fn uc_hook_del(uc: *mut uc_engine, hh: uc_hook) -> uc_err;
}
pub const UC_PROT_NONE: uc_prot = 0;
pub const UC_PROT_READ: uc_prot = 1;
pub const UC_PROT_WRITE: uc_prot = 2;
pub const UC_PROT_EXEC: uc_prot = 4;
pub const UC_PROT_ALL: uc_prot = 7;
pub type uc_prot = ::std::os::raw::c_int;
extern "C" {
    pub fn uc_mem_map(uc: *mut uc_engine, address: u64, size: usize, perms: u32) -> uc_err;
}
extern "C" {
    pub fn uc_mem_map_ptr(
        uc: *mut uc_engine,
        address: u64,
        size: usize,
        perms: u32,
        ptr: *mut ::core::ffi::c_void,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_mmio_map(
        uc: *mut uc_engine,
        address: u64,
        size: usize,
        read_cb: uc_cb_mmio_read_t,
        user_data_read: *mut ::core::ffi::c_void,
        write_cb: uc_cb_mmio_write_t,
        user_data_write: *mut ::core::ffi::c_void,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_mem_unmap(uc: *mut uc_engine, address: u64, size: usize) -> uc_err;
}
extern "C" {
    pub fn uc_mem_protect(uc: *mut uc_engine, address: u64, size: usize, perms: u32) -> uc_err;
}
extern "C" {
    pub fn uc_mem_regions(
        uc: *mut uc_engine,
        regions: *mut *mut uc_mem_region,
        count: *mut u32,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_context_alloc(uc: *mut uc_engine, context: *mut *mut uc_context) -> uc_err;
}
extern "C" {
    pub fn uc_free(mem: *mut ::core::ffi::c_void) -> uc_err;
}
extern "C" {
    pub fn uc_context_save(uc: *mut uc_engine, context: *mut uc_context) -> uc_err;
}
extern "C" {
    pub fn uc_context_reg_write(
        ctx: *mut uc_context,
        regid: ::std::os::raw::c_int,
        value: *const ::core::ffi::c_void,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_context_reg_read(
        ctx: *mut uc_context,
        regid: ::std::os::raw::c_int,
        value: *mut ::core::ffi::c_void,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_context_reg_write_batch(
        ctx: *mut uc_context,
        regs: *mut ::std::os::raw::c_int,
        vals: *const *mut ::core::ffi::c_void,
        count: ::std::os::raw::c_int,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_context_reg_read_batch(
        ctx: *mut uc_context,
        regs: *mut ::std::os::raw::c_int,
        vals: *mut *mut ::core::ffi::c_void,
        count: ::std::os::raw::c_int,
    ) -> uc_err;
}
extern "C" {
    pub fn uc_context_restore(uc: *mut uc_engine, context: *mut uc_context) -> uc_err;
}
extern "C" {
    pub fn uc_context_size(uc: *mut uc_engine) -> usize;
}
extern "C" {
    pub fn uc_context_free(context: *mut uc_context) -> uc_err;
}
